### ISSUE TITLE
"GitHub Dark" is missing..

### ISSUE THREAD

**Issue by ianpan870102** [primer/github-vscode-theme#10]
I'd love to give this theme a try, but after installing the extension on my VSCode, I only get the option "GitHub Light". I'm on Windows 10.
I have uninstalled and re-installed again, but "GitHub Dark" is still missing.
Let me know if you need more info.

**Comment by cdonohue** [comment]
@ianpan870102, I believe this is coming in a future release. The [VSCode Marketplace theme page](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme) still shows only the light theme, so I'd bet on the dark theme as an addition that is happening really soon based on the recent commits:

> https://github.com/primer/github-vscode-theme/commit/1d709fe2c0c89bb685f8a2b1113f847ea859ac24

**Comment by simurai** [comment]
> I believe this is coming in a future release.

👍  Yes, it's already in the `master` branch but not published yet. Still testing a bit more.

**Comment by DylanModesitt** [comment]
The dark theme still has a few unfinished edges (like autocomplete background) but it looks *so good*. Super excited for release.

**Comment by simurai** [comment]
Ok, the dark version should now be available on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme).
