### ISSUE TITLE
Automatically convert colors to the #RRGGBBAA format

### ISSUE THREAD

**Issue by simurai** [primer/github-vscode-theme#101]
## Problem

In PR https://github.com/primer/github-vscode-theme/pull/98 the colors from `@primer/primitives` use the `rgba()` format when they have transparency. But VS Code [only allows](https://code.visualstudio.com/api/references/theme-color#color-formats) the `#RRGGBBAA` format. When using `rgba()` it defaults to `red`:

![Screen Shot 2021-01-05 at 16 33 35](https://user-images.githubusercontent.com/378023/103618807-e8c52680-4f73-11eb-9b94-25a4c6e214d5.png)

## Current work-around

For now colors that use `rgba()` get wrapped with [`chroma(...).hex()`](https://gka.github.io/chroma.js/#color-hex) to convert them to the `#RRGGBBAA` format: https://github.com/primer/github-vscode-theme/blob/66bc8f0f9430b44e40da279f5c4fdd3d0c3b584a/src/theme.js#L165-L166

![Screen Shot 2021-01-05 at 16 38 27](https://user-images.githubusercontent.com/378023/103619127-84569700-4f74-11eb-89f9-4617849c18ec.png)

This works fine but every time we update `@primer/primitives` we have to manually check the generated theme if any of the colors started to use `rgba()` and then convert it with `chroma(...).hex()`.

## Long term solution

It's not super urgent, but it would be nice if `rgba()` could be converted automatically. I tried some regex find+replace but didn't get very far.

**Comment by hyrious** [comment]
Maybe we just dig into `colors` and change these `rgba(...)` ?
```js
function isstr(x) { return typeof x === 'string' }
function isobj(x) { return typeof x === 'object' && !Array.isArray(x) }
function dirtyFix(x) {
    if (isstr(x) && x.startsWith('rgba(')) {
        let rgba = x.substring('rgba('.length, x.indexOf(')')).split(',');
        if (rgba[3] === 1) {
            rgba = rgba.slice(0, 3);
        } else {
            rgba[3] = ~~(rgba[3] * 255);
        }
        return '#' + rgba.map(e => parseInt(e).toString(16).padStart(2, '0')).join('');
    }
    if (isobj(x)) {
        for (const key in x) {
            const val = x[key];
            x[key] = dirtyFix(val);
        }
    }
    return x;
}
dirtyFix(lightColors); // and so on
```

**Comment by simurai** [comment]
With the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202
