### ISSUE TITLE
Theme and text highlight not matching the new Github website dark theme

### ISSUE THREAD

**Issue by Iconejey** [primer/github-vscode-theme#103]
Github just released Dark Mode Beta for their website but the github-vscode-theme extension does not match it. An update is needed.

![VScode - Github com](https://user-images.githubusercontent.com/43481095/104072050-bcfaa880-51e0-11eb-9a42-fa974b8655cc.png)

**Comment by simurai** [comment]
> An update is needed.

👍  We have this PR https://github.com/primer/github-vscode-theme/pull/102 that tries to do that.
