### ISSUE TITLE
Whitespace contrast is too high with new dark color scheme

### ISSUE THREAD

**Issue by jacobwgillespie** [primer/github-vscode-theme#106]
Now that there's a new dark color scheme, whitespace characters seem to have a higher contrast than before and appear brighter, making it more difficult to focus on the code. Would it be possible to lower the brightness/contrast of the whitespace charaters under the new scheme?

**Current Example**

<img width="766" alt="Screenshot 2021-01-20 at 04 36 47" src="https://user-images.githubusercontent.com/130874/105127816-8aeb1f80-5ad9-11eb-8d64-456b5b504a3a.png">

**Comment by rogiervandenberg** [comment]
What happened? Overnight my IDE suddenly looks different. Is there now also an "github-vscode-theme dark classic" ? 🤔

**Comment by BerriJ** [comment]
Please don't drop support for the old dark theme. It was so much better.

**Comment by simurai** [comment]
> What happened? Overnight my IDE suddenly looks different. Is there now also an "github-vscode-theme dark classic" ?

Yes, see https://github.com/primer/github-vscode-theme/discussions/114 for more details.
