### ISSUE TITLE
the new dark theme,the menu's font is low bright and too grey, it looks very strenuous

### ISSUE THREAD

**Issue by Oliver-zg** [primer/github-vscode-theme#107]
include terminal,explorer and so on

**Comment by vinkla** [comment]
Here is an example where we could improve the contrast:

![CleanShot 2021-01-21 at 08 53 52@2x](https://user-images.githubusercontent.com/499192/105320860-ff4fbc80-5bc6-11eb-950b-79e3821d22ad.png)

**Comment by simurai** [comment]
> Here is an example where we could improve the contrast:

👍  Should be improved with https://github.com/primer/github-vscode-theme/pull/117
