### ISSUE TITLE
very contrasting black color

### ISSUE THREAD

**Issue by from0toweb** [primer/github-vscode-theme#108]
very contrasting black color. The old version was the only one from the entire marketplace that could be used, but the changes apparently went not for the better for me

**Comment by cmcarey** [comment]
Agreed. Now it looks more like a high contrast theme than the very nice aesthetic it used to have.

**Comment by gargakshit** [comment]
Apparently it is done to match GitHub's dark theme. Current workaround for me was to install version 1.15. It is available after you click the dropdown after "uninstall"

![image](https://user-images.githubusercontent.com/15605299/105161827-d3392a80-5b37-11eb-9df9-beef245bd8d5.png)

**Comment by from0toweb** [comment]
> Видимо, это сделано для соответствия темной теме GitHub. Текущий обходной путь для меня заключался в установке версии 1.15. Он доступен после того, как вы нажмете раскрывающийся список после «удалить».
> 
> ![образ](https://user-images.githubusercontent.com/15605299/105161827-d3392a80-5b37-11eb-9df9-beef245bd8d5.png)

It's not a problem! Something new should be better than old, but for me the old version is better. I am back to the old version

**Comment by gargakshit** [comment]
> > Видимо, это сделано для соответствия темной теме GitHub. Текущий обходной путь для меня заключался в установке версии 1.15. Он доступен после того, как вы нажмете раскрывающийся список после «удалить».
> > ![образ](https://user-images.githubusercontent.com/15605299/105161827-d3392a80-5b37-11eb-9df9-beef245bd8d5.png)
> 
> It's not a problem! Something new should be better than old, but for me the old version is better. I am back to the old version

Agreed, the old version looked a lot better

**Comment by Robouste** [comment]
I was so happy with the previous theme, which was the best ever to me.

Now, I don't like it, at all.

We should be able to choose between old & new without having to downgrade the extension.

**Comment by larsbs** [comment]
I understand that they wanted to be coherent with their themes, but first, I don't think a website in dark mode is comparable to an editor theme (different usage patterns and all of that) and second, the contrast ratio in the old one was perfect and this one looks like some others have mentioned, like a high contrast theme and puts a lot of strain in the eyes. Definitely, going back to the older version.

**Comment by ccidral** [comment]
Can we keep the old theme as a separate theme, like a legacy theme or something? I know you want to keep it consistent with Github's theme but the new one looks horrible.

**Comment by manuelricci** [comment]
You can install the classic dark theme via VSIX with the files in [this repo](https://github.com/primer/github-vscode-theme-dark-classic)

**Comment by botex98** [comment]
Personally I would suggest adding a 3rd support theme, so rename the old one to `GitHub Classic Dark` and everyone is happy.

**Comment by progapandist** [comment]
Please keep old muted colors, pretty please please please

**Comment by Rec0iL99** [comment]
I don't know if this is just me, but my eyes started paining after using the new update for the theme. Changed back to the default vs code theme.

**Comment by mjyocca** [comment]
I get the point of the change to match dark mode on github, but I think it should be the reverse. Github should match the color theme of the `Github Classic Dark` haha 😆

**Comment by jackdcasey** [comment]
I agree with @botex98, a "new" theme of "Github Dark Classic" should make everyone happy 😄 

I've reviewed a diff between `v1.5.5 and v2.0.0` and the difference is fairly large. I'll try to find some time to test out adding this new theme. If I can get it sorted out, I'll post a PR soon

**Comment by itsMapleLeaf** [comment]
I don't even think the new theme is _bad_, but the change was so drastic, I thought something was broken at first. The main problem is that it's practically an entire new syntax theme now.

**Comment by codeinclined** [comment]
I had the same reaction as @itsMapleLeaf. I thought something broke in VSCode until I remembered "Oh yeah, this looks like the website's new NEED MOAR BLACK" dark theme. I'm going to either downgrade to 1.1.5 or find a new theme now.

**Comment by simurai** [comment]
> @ccidral Can we keep the old theme as a separate theme

Yes, as mentioned by @manuelricci:

> You can install the classic dark theme via VSIX with the files in [this repo](https://github.com/primer/github-vscode-theme-dark-classic).

Also added a new Discussion https://github.com/primer/github-vscode-theme/discussions/114 with a short FAQ.

**Comment by antoineboulanger** [comment]
I agree that the new theme has way more contrast than GitHub's dark mode. None of the colours match.

**Comment by simurai** [comment]
Sorry for the inconvenience 🙇, with the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202

**Comment by paramaggarwal** [comment]
This is an official GitHub theme meant to replicate the Github.com themes within your local VSCode IDE. This extension should not honour user's personal preferences and resistance to change. It was supposed to be un-opinionated. When GitHub updates their colour scheme, will we introduce another new variation of these themes in this extension!
