### ISSUE TITLE
Low contrast on quick pick items

### ISSUE THREAD

**Issue by misolori** [primer/github-vscode-theme#109]
While I'm trying to get used to the new colors (previous one felt better) I noticed that the command palette had low contrast for entry items and wasn't sure if that was a mistake or intentional (to me it stood out like a bug). Also, the colors of the focus item and regular foreground feels off.

![image](https://user-images.githubusercontent.com/35271042/105199931-2a1d1080-5af4-11eb-9a4e-b780f7441179.png)

Here's what I've tweaked my version to look like, re-using other colors from the list colors:

```json
    "list.highlightForeground": "#1f6feb",
    "list.focusBackground": "#161b22"
    "quickInput.foreground": "#c9d1d9",
```

![image](https://user-images.githubusercontent.com/35271042/105200636-e8d93080-5af4-11eb-8566-2b0821f8d190.png)

**Comment by simurai** [comment]
> command palette had low contrast

Ahh.. yes. That could be improved. 👍  Started a PR here https://github.com/primer/github-vscode-theme/pull/117
