### ISSUE TITLE
Hovered context menu items are invisible with dark theme + custom menus

### ISSUE THREAD

**Issue by kdrag0n** [primer/github-vscode-theme#11]
If `window.titleBarStyle` is set to `custom` on Windows or Linux and the GitHub Dark theme is active, the hovered item is invisible in context menus:
![image](https://user-images.githubusercontent.com/7930239/81238287-7c45f200-8fb6-11ea-921b-e790b5c2203e.png)

For reference, the light theme is fine:
![image](https://user-images.githubusercontent.com/7930239/81238263-70f2c680-8fb6-11ea-830e-272b23deb044.png)

**Comment by simurai** [comment]
@kdrag0n Thanks for reporting. 🙇 

PR #13 is now merged into `master`, if you wanna test again. I'm using macOS which I think doesn't have these custom context menus even when `window.titleBarStyle` is set to `custom`. But I think it's the `list.activeSelectionBackground` token that needed to be changed.

**Comment by kdrag0n** [comment]
Thanks for the quick fix, it works fine now:
![image](https://user-images.githubusercontent.com/7930239/81352271-fd66bd00-907a-11ea-9c4a-d92bfe1223eb.png)
