### ISSUE TITLE
new dark theme sucks

### ISSUE THREAD

**Issue by rhyek** [primer/github-vscode-theme#110]

**Comment by Orekiz** [comment]
i think so

**Comment by 0xxd0** [comment]
It's too dark, just like a high contrast theme

**Comment by on3dd** [comment]
Totally agree! 👍

**Comment by Vitor-Carmo** [comment]
I totally agree with it! 👍
I had to downgrade the extension to use the previous one

**Comment by NuroDev** [comment]
Agreed. I feel like the old theme (Now called [github-vscode-theme-dark-classic](https://github.com/primer/github-vscode-theme-dark-classic)) should be bundled with the standard GitHub theme and the new 2.0.0 dark theme should be labelled "High Contrast" or "Pure black" or something similar. Seems more fitting.

**Comment by JosephTLyons** [comment]
I like the colors when they are on GitHub.com, but for some reason, they don't really work well for me on VS Code.

**Comment by minimaxir** [comment]
The approach of [GitHub Dark Turbo](https://marketplace.visualstudio.com/items?itemName=DubeSoftware.github-dark-turbo) was a good balance between the old dark theme and the new 2.0.0 dark theme.

**Comment by sdttttt** [comment]
[Atomized Theme](https://marketplace.visualstudio.com/items?itemName=excalith.atomized-theme) is very similar to the original GitHub Dark, perhaps as an alternative.

**Comment by simurai** [comment]
Also see this short FAQ that has some more details.

**Comment by hackingguy** [comment]
And from 2 days I was thinking I got some issue in VSCode 😒

**Comment by benalexb** [comment]
@simurai available, but for how long? It's not officially maintained (the repo even says as much)... at some point it will no longer work properly.

**Comment by simurai** [comment]
Sorry for the inconvenience 🙇, with the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202
