### ISSUE TITLE
New Theme feedback on the release

### ISSUE THREAD

**Issue by miralize** [primer/github-vscode-theme#112]
I understand the main reasoning behind it was to [align with](https://github.com/primer/github-vscode-theme/issues/103) the recently released (and for me personally an equally eye-straining) Dark Mode on Github.

However I'm unsure about the process behind releasing this over a theme that was relatively popular, actively used by thousands and effectively replacing it for people without consent or prior warning? Not only that but the "classic" version of Github Dark is not on the marketplace, which imo creates friction, in that if people want the classic version, they need to install the vsix directly.

There's little that can be done now, but I'm slightly annoyed by all of this. Perhaps a better way to go about this would have been to introduce the new Github Dark as another variant? Was there an immediate need to deprecate the original?

I'm hesitant to be overly critical as it looks like a lot of work went into the new theme, but maybe there could be some common ground here? And hopefully a bit better communication in the future

**Comment by codeforcesmeme** [comment]
I agree with the point you have. A **theme is a theme** it just doesn't make any sense to basically make a complete do over and call it `a breaking change update` or `version 2.0.0` under the same name as the old _theme_ leaving the old one as a binary somewhere on the internet.

With a big user base like this it should have been considered that such change would break the 'un-spoken' contract for all themes which is this theme looks like x and we like it and will use it daily, so we expect it to look like this forever with minor regular enhancements.

**Comment by ashgkwd** [comment]
I love the old theme. New one makes my eyes sink in the Abyss. **As a workaround, you can continue using version 1.x on VS Code.**

## Steps

1. Install the **GitHub Theme**. It will install version 2.x as this is the latest
1. After installation, in the extensions sidebar, select **GitHub Theme**
1. Click on gear icon (settings icon) --> Install Another Version
1. Select latest of 1.x versions
1. Click on Reload for the selected version to take effect :dancers: 

![Screenshot from 2021-01-21 06-53-07](https://user-images.githubusercontent.com/5814056/105261287-619fc180-5bb5-11eb-98e2-1326ee15e303.png)

**Comment by simurai** [comment]
> @miralize Perhaps a better way to go about this would have been to introduce the new Github Dark as another variant?

We were considering just using a different name for the new dark theme. But that could be confusing when a user sees the `Dark` theme on github.com's [settings](https://github.com/settings/appearance) but in VS Code it would be called something different. So keeping the themes in sync felt the best way long term.

Also this theme gets used for https://github.com/codespaces. So when a user opens a Codespace, it's nice if the colors still are the same.

> @codeforcesmeme so we expect it to look like this forever

Yeah, I agree that keeping themes more or less the same would avoid any unpleasant surprises. But in this case it's GitHub's "official" theme. So we felt it's best to keep it as close as possible to the [themes available on github.com](https://github.com/settings/appearance).

> @ashgkwd As a workaround, you can continue using version 1.x on VS Code.

👍  Another option is to install it via `.vsix` from the [github-vscode-theme-dark-classic](https://github.com/primer/github-vscode-theme-dark-classic) repo. See [Install](https://github.com/primer/github-vscode-theme-dark-classic#install) in the README.

ps. added a new Discussion https://github.com/primer/github-vscode-theme/discussions/114 with a short FAQ.

**Comment by RA80533** [comment]
> 👍 Another option is to install it via .vsix from the github-vscode-theme-dark-classic repo.

Is there a corresponding version for the old light theme?

**Comment by simurai** [comment]
> Is there a corresponding version for the old light theme?

The `GitHub Light` hasn't changed and should still look the same.

**Comment by RA80533** [comment]
@simurai See #115 for a comparison.

**Comment by rhyek** [comment]
Why not just reintroduce the old variant and call it Dark Classic and that way you spare people having to fiddle with binaries that may cause issues already such as not playing nice with settings sync?

Or maybe this theme needs a fork and someone can publish Dark Classic individually.

**Comment by simurai** [comment]
> Why not just reintroduce the old variant and call it Dark Classic

We were considering that, but then people expect it to be an actively maintained theme just like the `Light` and new `Dark`. So having to install it via `.vsix` from the [github-vscode-theme-dark-classic](https://github.com/primer/github-vscode-theme-dark-classic) repo makes it more clear that it's not part of the "official" GitHub themes that are also available on [github.com](https://github.com/settings/appearance).

> Or maybe this theme needs a fork and someone can publish Dark Classic individually.

Yes, if anyone wants to fork and publish it to the marketplace, feel free. 👍  It probably will keep working until VS Code changes how themes works.. maybe in a future `2.0`. But until then it should be fine as is.

**Comment by geocfu** [comment]
@simurai 

I think that the best approach would be if you didn't change the theme colors out of the blue, but add a new theme entry named "GitHub Dark Classic".
I definitely appreciate the work behind the new changes, but changing a theme that we installed based on the previous color palette and don't giving us an option is not how themes should be. For example, because the update on my machine happened when I was working, I thought that my machine probably got faulty at the time. It really took me some time to find this thread here to see that this was something intentional. (Besides the 2 reboots that I performed thinking that probably my drivers when nuts)

While yes, the GitHub Dark theme must be in par with the new official dark theme, deprecating the old and changing it for all those people that had the theme installed for the previous color palette, is not a move to be done, at least in the scale that this theme has come. 

As already stated by other users, you could keep the old palette as Classic inside the theme. This way, all of us that liked the old theme can benefit from any bug fixes or improvements and the ones that prefer the new one can get the same experience.

I ended up uninstalling the theme because installing the classic version from the README seemed like it has now become deprecated. As a result, it will not receive new updates or fixes. 

I sincerely believe that you should rethink the way you implemented such a breaking change and take into account the negative feedback this has created, both here and in the VS Marketplace.

At last, thank you very much for the endless hours of eye pleasing experience you gave with your theme.

Happy new Year 🎉

**Comment by BerriJ** [comment]
I just published it [here](https://marketplace.visualstudio.com/items?itemName=BerriJ.github-vscode-theme-dark-classic).

**Comment by yamatsum** [comment]
> Also this theme gets used for https://github.com/codespaces. So when a user opens a Codespace, it's nice if the colors still are the same.

Instead of changing this theme, I think codespaces's theme and github.com's dark theme that should be changed.
Many people feel that the black color of v2 is too contrasting.

**Comment by miralize** [comment]
Thanks for the response @simurai. 

Another option could be to publish the variant in the same theme with a new name `Github Dark Classic (not maintained)` `Github Dark Classic (deprecated)`. It would  still manage expectations, but would also provide an easy path for people.

**Comment by BerriJ** [comment]
> Thanks for the response @simurai. 
> 
> Another option could be to publish the variant in the same theme with a new name `Github Dark Classic (not maintained)` `Github Dark Classic (deprecated)`. It would  still manage expectations, but would also provide an easy path for people.

Look 2 posts above yours. It's already published as "Github Dark Classic Theme".

**Comment by miralize** [comment]
> > Thanks for the response @simurai.
> > Another option could be to publish the variant in the same theme with a new name `Github Dark Classic (not maintained)` `Github Dark Classic (deprecated)`. It would  still manage expectations, but would also provide an easy path for people.
> 
> Look 2 posts above yours. It's already published as "Github Dark Classic Theme".

I can understand that its already published. My point is that its still not a great solution. Having the deprecated variant under this "theme" still means the user has less to do to migrate to the theme they *did* pick.

**Comment by rhyek** [comment]
I installed @BerriJ 's theme and this solves my problem nicely. Thanks!

**Comment by simurai** [comment]
Sorry for the inconvenience 🙇, with the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202

**Comment by paramaggarwal** [comment]
The revert made due to this thread was a step backwards. This is meant to be the "GitHub Theme", it should update hand in hand with Github.com, it's not meant to respect user's personal preferences and resistance to change.
