### ISSUE TITLE
Ignored files look almost the same as tracked files in the explorer pane

### ISSUE THREAD

**Issue by RA80533** [primer/github-vscode-theme#115]
I've included two screenshots sourced directly from this repository to illustrate the issue. Take note of the node_modules folder shown in the explorer pane.

### Before
![](https://user-images.githubusercontent.com/378023/80668639-595e9e00-8add-11ea-8673-4a481cc7e2dd.png)

### After
![](https://user-images.githubusercontent.com/378023/105131643-b64b2a00-5b2c-11eb-886f-622e4dc46187.png)

**Comment by simurai** [comment]
@RA80533 Ah.. I see. You meant for the `Light` theme? Yes, that could be improved. 👍
