### ISSUE TITLE
The hover effect on context menu doesn't reflect much

### ISSUE THREAD

**Issue by max-programming** [primer/github-vscode-theme#116]
Just realized that the theme is updated and it looks absolutely awesome! But the context menu has a hover effect which only changes the text color. Can we please also have a background of the item change as the older one?

![image](https://user-images.githubusercontent.com/51731966/105282392-3d9fa880-5bd4-11eb-92e1-851ce5f649f3.png)

![image](https://user-images.githubusercontent.com/51731966/105282367-32e51380-5bd4-11eb-8fbc-bba918004b7f.png)

**Comment by simurai** [comment]
Thanks for reporting, with the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202
