### ISSUE TITLE
Variant for 1.1.5 dark theme

### ISSUE THREAD

**Issue by benalexb** [primer/github-vscode-theme#120]
The dark version of this theme has been my favorite of all time, for a long time... I suffer from chronic photophobia, so it's very hard for me to find a suitable theme and get used to it. For now, I have installed the older version (1.1.5). I have also noticed the community is forking the project to preserve the old theme, but the forks are not maintained. Would it be possible to create a variant of the theme with the same palette from 1.1.5? This would be the most sensible course of action in my honest opinion, so the community can continue enjoying the theme as it was, with all the support it already has.

At any rate, I would like to thank you for all the hard work you have already put into this theme, thank you!

**Comment by simurai** [comment]
Sorry for the inconvenience 🙇, with the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202
