### ISSUE TITLE
[regression] Selection colors don't work with diff-colors anymore

### ISSUE THREAD

**Issue by jrieken** [primer/github-vscode-theme#121]
* using 2.0.1
* using light theme
* havechanges under git
* make a selection in an added or removed region
* the selection isn't visible, it doesn't blend with the diff regions

In the screen shot below my selection goes from line 165 to 172

<img width="438" alt="Screenshot 2021-01-22 at 16 40 51" src="https://user-images.githubusercontent.com/1794099/105513575-c6047300-5cd2-11eb-9581-8161dfc0fd0d.png">

**Comment by simurai** [comment]
Thanks for reporting... with the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202
