### ISSUE TITLE
Version 2.0.1 published theme files are incorrect

### ISSUE THREAD

**Issue by jacobwgillespie** [primer/github-vscode-theme#122]
Hey, it looks like when v2.0.1 was published, the `themes` directory JSON files were not regenerated with `npm run build` beforehand, and so appear to be missing the fixes from #117.

Here's a screenshot, the left hand side is `dark.json` after cloning the repo locally and building `v2.0.1`, the right is the published `dark.json` from the VS Code extension package:

<img width="1420" alt="Screenshot 2021-01-22 at 21 42 18" src="https://user-images.githubusercontent.com/130874/105551552-b731b680-5cfa-11eb-80e8-74303d68cd52.png">

**Comment by SamuelQuinones** [comment]
I also have this problem, results and findings are the same as the initial post

**Comment by simurai** [comment]
I might have missed to re-build the theme? Anyways...

...with the `3.0.0` release, this theme should be back to how it used to be a couple days ago. More details here https://github.com/primer/github-vscode-theme/discussions/114#discussioncomment-304202
