### ISSUE TITLE
Please adjust background colour

### ISSUE THREAD

**Issue by mishushakov** [primer/github-vscode-theme#124]
Hi there,
not happy with the latest update

the colours don't match

GitHub

<img width="551" alt="Screenshot 2021-01-23 at 15 08 43" src="https://user-images.githubusercontent.com/10400064/105580508-1cce8300-5d8d-11eb-9b74-66accee79c3f.png">

VSCode

<img width="683" alt="Screenshot 2021-01-23 at 15 08 18" src="https://user-images.githubusercontent.com/10400064/105580505-16400b80-5d8d-11eb-88bf-6c1b3f3119b8.png">

Sample Code

https://github.com/GuitarML/PedalNetRT/blob/master/test.py

thanks a lot for the theme!

**Comment by DrPepperG** [comment]
#123 Removed the new dark mode

**Comment by simurai** [comment]
This should be resolved and backgrounds should match github.com
