### ISSUE TITLE
It is not clear which option it focuses on in the auto complete part.

### ISSUE THREAD

**Issue by eneskutlay** [primer/github-vscode-theme#125]
<img width="369" alt="Adsız" src="https://user-images.githubusercontent.com/59585311/105616985-3357f700-5dec-11eb-819d-5b4e44f3d942.png">

**Comment by simurai** [comment]
This should be resolved:

![image](https://user-images.githubusercontent.com/378023/179174370-26f7f34b-3c3a-4f00-bac0-27ea1f8e894d.png)
