### ISSUE TITLE
Multiline string highlight

### ISSUE THREAD

**Issue by rhyek** [primer/github-vscode-theme#128]
This is hard to read:

![image](https://user-images.githubusercontent.com/702922/106167279-a77afd80-6152-11eb-8a2c-08ce1e32b3cd.png)

I've usually seen themes just provide a background for highlighted text instead of the outline. Might help. Thanks.

**Comment by diminutivesloop** [comment]
This was fixed in TypeScript 4.6.0 https://github.com/microsoft/TypeScript/issues/43292
