### ISSUE TITLE
Punctuation.definition.string - Too high priority

### ISSUE THREAD

**Issue by jaymegordo** [primer/github-vscode-theme#133]
I'd like to request that you please remove `punctuation.definition.string` from the vscode-github theme, and replace it with lower priority values, eg:
- `string.quoted.docstring`
- `string.quoted.single`

etc, I'm sure there's a few more.

`punctuation.definition.string` is just too high priority and overwrites all string punctuation, which prevents further customization. Eg I'd like to be able to set different colors for normal strings vs docstrings (in python).

Overall though amazing theme, thanks!!

**Comment by jaymegordo** [comment]
Commenting again because I see that 4.0.0 is out now but this hasn't been fixed.

in the `~/.vscode/extensions/github.github-vscode-theme-4.0.0/themes/dark.json` file, I'm just commenting out this part and it makes the theme more flexible to define colors for different types of strings.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/29611875/114749286-a300c280-9d07-11eb-9011-c5d0f145cdf0.png">

**Comment by jaymegordo** [comment]
Any plans to remove this? would be really appreciated!!

**Comment by jaymegordo** [comment]
Another github-vscode-theme released `4.2.1` but this hasen't been fixed yet... please please fix thank you!!

**Comment by jaymegordo** [comment]
`5.0.0` out but still not changed... cmon how hard can this be!! Just break `punctuation.definition.string` into a couple less high-priority categories??

**Comment by jaymegordo** [comment]
`5.2.2` out now, STILL not fixed please fix thanks!!

**Comment by simurai** [comment]
Sorry it took so long. `punctuation.definition.string` should be removed in the next release.

**Comment by jaymegordo** [comment]
I'm on 6.3.3 and this still exists in `dark.json`...



![Image](https://user-images.githubusercontent.com/29611875/213585345-3d8a2cff-dbd5-4245-93ae-38c046be38ed.png)
