### ISSUE TITLE
Hovered command palette item color is invisible with dark theme

### ISSUE THREAD

**Issue by kdrag0n** [primer/github-vscode-theme#14]
Normally, when hovering items in the command palette, there's a visible difference in the item's background color to differentiate it from the rest, but the highlight is invisible when using the dark theme.

Light (notice how the Toggle Developer Tools item is hovered):
![image](https://user-images.githubusercontent.com/7930239/81351815-0905b400-907a-11ea-85c3-86b2fbabeb41.png)

Dark:
![image](https://user-images.githubusercontent.com/7930239/81351883-20dd3800-907a-11ea-877b-62aa94b0df6d.png)

**Comment by Mayuyu** [comment]
Anyone is working on this?
