### ISSUE TITLE
Highlighted Text Color disappears when Block is Fold

### ISSUE THREAD

**Issue by RuizuKun-Dev** [primer/github-vscode-theme#140]
**Unfold:**
![image](https://user-images.githubusercontent.com/55673217/112608503-fb514c80-8e4c-11eb-8a21-03c6e5f2d337.png)

**Fold:**
![image](https://user-images.githubusercontent.com/55673217/112608470-ef658a80-8e4c-11eb-9524-1f378caba599.png)

**GIF:**

[![Image from Gyazo](https://i.gyazo.com/9e1a7610e94dffb14134460e3564aa6d.gif)](https://gyazo.com/9e1a7610e94dffb14134460e3564aa6d)
___

That is Lua language

**Comment by kevinfarrugia** [comment]
Duplicates #131 and #53 .

> I was able to workaround by setting `editor.foldingHighlight: false` in `settings.json`.

**Comment by simurai** [comment]
@RuizuKun-Dev Thanks for reporting. 🙇 

> Duplicates #131 and #53 .
> 
> > I was able to workaround by setting `editor.foldingHighlight: false` in `settings.json`.

@kevinfarrugia thanks for pointing out the workaround. That's good to know. Would still be nice to look into if it's possible to add a highlight color to folded lines. I'll close this as duplicate for now.
