### ISSUE TITLE
Style `"editor.linkedEditing": true`

### ISSUE THREAD

**Issue by muuvmuuv** [primer/github-vscode-theme#141]
![Bildschirmfoto 2021-04-08 um 08 15 00](https://user-images.githubusercontent.com/11534760/113977245-97625700-9842-11eb-8217-49a647be9729.png)

It is a new VS Code feature to e.g. rename similar tags in HTML.

**Comment by dominicegginton** [comment]
I believe this is a user-defined setting within VSCode or am I wrong?

**Comment by muuvmuuv** [comment]
Yeah, it is a new setting introduces recently. It should make all "rename similar tags" extensions obsolete.
