### ISSUE TITLE
base16 implementation

### ISSUE THREAD

**Issue by jef** [primer/github-vscode-theme#149]
> **Preface:** I'm not really sure where to put this, so I'm doing it here. (Sorry in advanced.)

### Description

I'd love to take a stab or get some guidance on implementing this into [base16](https://github.com/chriskempson/base16).

The scheme is defined as such:

> - **base00** - Default Background
> - **base01** - Lighter Background (Used for status bars, line number and folding marks)
> - **base02** - Selection Background
> - **base03** - Comments, Invisibles, Line Highlighting
> - **base04** - Dark Foreground (Used for status bars)
> - **base05** - Default Foreground, Caret, Delimiters, Operators
> - **base06** - Light Foreground (Not often used)
> - **base07** - Light Background (Not often used)
> - **base08** - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
> - **base09** - Integers, Boolean, Constants, XML Attributes, Markup Link Url
> - **base0A** - Classes, Markup Bold, Search Text Background
> - **base0B** - Strings, Inherited Class, Markup Code, Diff Inserted
> - **base0C** - Support, Regular Expressions, Escape Characters, Markup Quotes
> - **base0D** - Functions, Methods, Attribute IDs, Headings
> - **base0E** - Keywords, Storage, Selector, Markup Italic, Diff Changed
> - **base0F** - Deprecated, Opening/Closing Embedded Language Tags, e.g. `<?php ?>`

And put into a YAML files that could look like [this repository](https://github.com/dawikur/base16-gruvbox-scheme).

This would give users that use base16 a great way to integrate all their schemes to match GitHub's new dark and dimmed variances.

Are you able to point me in the right direction of where these primer colors are the specify which color is used for what type of component?

Thanks!

**Comment by dominicegginton** [comment]
Hi @jef

You can take a look at [primer/primitives](https://github.com/primer/primitives) for color values and [theme.js](https://github.com/primer/github-vscode-theme/blob/master/src/theme.js) for the implementation of them into the GitHub VSCode theme. You may want to clone [primer/primitives](https://github.com/primer/primitives) and build. Hope this helps 😄

**Comment by jef** [comment]
Aha, okay. So after building, I basically map this:

https://github.com/primer/github-vscode-theme/blob/39d5cf169b3d6c0c28d805184afbda99866874b5/src/colors.js#L1-L3

With this, basically:

https://github.com/primer/github-vscode-theme/blob/39d5cf169b3d6c0c28d805184afbda99866874b5/src/theme.js#L12-L562

Great! This may be a good start. I appreciate your help.
