### ISSUE TITLE
(`GitHub Dark Default` and `GitHub Dark Dimmed`) disabled extensions are difficult to distinguish

### ISSUE THREAD

**Issue by darkred** [primer/github-vscode-theme#159]
Using the extension v4.0.2 with VSCode 1.55.2 on windows 10.

I've noticed that when using the `GitHub Dark Default` and `GitHub Dark Dimmed` themes,
the disabled extensions are difficult to distinguish.

Screenshot comparison:
[Light+ (default light)](https://user-images.githubusercontent.com/723651/115116286-7962c800-9fa1-11eb-929c-a374fbb31b2f.jpg) <-- ok
[Dark+ (default dark)](https://user-images.githubusercontent.com/723651/115116289-7b2c8b80-9fa1-11eb-80dc-73064df6433a.jpg) <-- ok

[GitHub Dark Default](https://user-images.githubusercontent.com/723651/115116291-7cf64f00-9fa1-11eb-992f-72ad037af1ce.jpg) <-- difficult to distinguish
[GitHub Dark Dimmed](https://user-images.githubusercontent.com/723651/115116296-8089d600-9fa1-11eb-9b86-dfb15189d164.jpg) <-- almost indistinguishable

I'm aware that you have released these GitHub.com themes just a few days ago, I just wanted to mention this to you.

Thank you

**Comment by dominicegginton** [comment]
A fix (#158) has already been submitted and is awaiting approval and merge
