### ISSUE TITLE
Autocomplete background still uses the default color

### ISSUE THREAD

**Issue by simurai** [primer/github-vscode-theme#16]
![image](https://user-images.githubusercontent.com/378023/81362309-82091800-911b-11ea-9380-77f52731d678.png)

---

Reported in https://github.com/primer/github-vscode-theme/issues/10#issuecomment-625309160

**Comment by paulomenezes** [comment]
Is the find/replace background also with the default color?

<img width="606" alt="image" src="https://user-images.githubusercontent.com/10564179/81452124-6ffb9980-915c-11ea-8428-d1005465cde6.png">

**Comment by this-fifo** [comment]
That's the `editorWidget.background` color, I think using the same color as the `panel.background` makes it look nicer I'll open a PR for it as a suggestion, here's how it looks like

Before
<img width="739" alt="image" src="https://user-images.githubusercontent.com/6960701/81842861-c2510780-951a-11ea-9741-294c10ece432.png">

After
<img width="721" alt="image" src="https://user-images.githubusercontent.com/6960701/81842887-c8df7f00-951a-11ea-8805-755fcb16ed3a.png">
