### ISSUE TITLE
Theme Dark Contrast

### ISSUE THREAD

**Issue by gperdomor** [primer/github-vscode-theme#161]
This image reflect the problem with some text in the integrated terminal...

<img width="227" alt="Screen Shot 2021-04-19 at 9 47 13 PM" src="https://user-images.githubusercontent.com/371939/115325012-e4a2ca80-a158-11eb-94ed-7dabad265f12.png">

The same terminal, but with some selected text... 
<img width="342" alt="Screen Shot 2021-04-19 at 9 47 23 PM" src="https://user-images.githubusercontent.com/371939/115325013-e53b6100-a158-11eb-99f5-4a556afb94a2.png">

**Comment by dominicegginton** [comment]
Hi @gperdomor

Are you using the latest release of the theme? The recent [v4.0.3](https://github.com/primer/github-vscode-theme/releases/tag/v4.0.3) release includes a fix (#160) that solved some contrast for the integrated terminal.

**Comment by CarlosGomez-dev** [comment]
Same issue on my system, running v.4.0.3.

`null` is almost invisible on Light Default, and `undefined` is very hard to see on Dark Default and Dark Dimmed.

GitHub Light
![image](https://user-images.githubusercontent.com/76704548/115426511-916b5f00-a1ce-11eb-97cc-ef9c466b6d56.png)
GitHub Dark
![image](https://user-images.githubusercontent.com/76704548/115426609-a9db7980-a1ce-11eb-97b6-3c83fc2da5c7.png)
GitHub Light Default
![image](https://user-images.githubusercontent.com/76704548/115426683-bcee4980-a1ce-11eb-88ca-50c9afaca409.png)
GitHub Dark Default
![image](https://user-images.githubusercontent.com/76704548/115426721-c7104800-a1ce-11eb-84d0-bf0bc0a89c4c.png)
GitHub Dark Dimmed
![image](https://user-images.githubusercontent.com/76704548/115426783-d5f6fa80-a1ce-11eb-98df-7c5b2d0252f6.png)

**Comment by gperdomor** [comment]
GitHub Light Default 
<img width="409" alt="Screen Shot 2021-04-20 at 1 03 43 PM" src="https://user-images.githubusercontent.com/371939/115437542-4e16ed80-a1da-11eb-9abe-b2ac9c67cf1e.png">

**Comment by simurai** [comment]
What command did you run see the output with `null` or `undefined`?

I found `msgcat --color=test` that outputs:

![Screen Shot 2021-04-21 at 23 21 57](https://user-images.githubusercontent.com/378023/115569783-84e32580-a2f8-11eb-9bea-2082dbd34683.png)

Or from [here](https://askubuntu.com/a/803316):

```bash
echo -e "\033[0mNC (No color)"
echo -e "\033[1;37mWHITE\t\033[0;30mBLACK"
echo -e "\033[0;34mBLUE\t\033[1;34mLIGHT_BLUE"
echo -e "\033[0;32mGREEN\t\033[1;32mLIGHT_GREEN"
echo -e "\033[0;36mCYAN\t\033[1;36mLIGHT_CYAN"
echo -e "\033[0;31mRED\t\033[1;31mLIGHT_RED"
echo -e "\033[0;35mPURPLE\t\033[1;35mLIGHT_PURPLE"
echo -e "\033[0;33mYELLOW\t\033[1;33mLIGHT_YELLOW"
echo -e "\033[1;30mGRAY\t\033[0;37mLIGHT_GRAY"
```

![Screen Shot 2021-04-21 at 23 24 10](https://user-images.githubusercontent.com/378023/115569996-b5c35a80-a2f8-11eb-9c8f-9aa9f0c55b37.png)

So I guess `WHITE` shouldn't really be "white" and more a light gray that is still visible on a light background? That's how the [default](https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts#L160) seems to be.

**Comment by CarlosGomez-dev** [comment]
> What command did you run see the output with `null` or `undefined`?

I ran this code for my screenshots:

```javascript
console.log('console undefined:', undefined);
console.log('console null:', null);
console.log('console string:', 'string');
console.log('console number:', 15);
console.log('console object:', {
  undefined: undefined,
  null: null,
  string: 'string',
  number: 15,
});
```

**Comment by simurai** [comment]
This should be improved in version [`4.0.4`](https://github.com/primer/github-vscode-theme/releases/tag/v4.0.4).

Also see https://github.com/primer/github-vscode-theme/issues/155#issuecomment-823987855.
