### ISSUE TITLE
Keep vscode default editor color theme

### ISSUE THREAD

**Issue by li1234yun** [primer/github-vscode-theme#174]
Hi,
I want to know that how can I use `github theme's editor UI`, but still use the vscode default `code color theme`.
Can you think of providing some settings to achive this?

Thank you!

**Comment by simurai** [comment]
👋  Hi. I don't think that's possible. A VS Code theme changes colors for both, the UI **and** the code. The only way I can think of is to create a new theme that combines github's and vscode default into a new theme. But we have no plans for that and someone from the community would need to give that a try.

**Comment by dominicegginton** [comment]
You could use the official GitHub theme for vscode. Then override the color theme in your user settings by setting values for syntax and other UI elements that you want to change back to default. Take a look [here](https://youtu.be/HhZcAhb-Sbk) for documentation about how to override ui colors. It might take a while to get setup but apart from creating a whole new theme this is the best solution I can think off.

**Comment by li1234yun** [comment]
Thank you both！
