### ISSUE TITLE
Red and green colors in the Working Tree should have more contrast

### ISSUE THREAD

**Issue by nil** [primer/github-vscode-theme#18]
![Github theme](https://user-images.githubusercontent.com/13088397/81378485-abb84400-9107-11ea-832c-40f080d47f4c.jpg)

On the split view that previews the difference between the old and modified file, modified lines have a red (for removed) and green (for added). These colors don't have enough contrast and they are quite difficult to spot, specially the reds.

Also, the actual changed text has a different background, but with the current colors it is almost impossible to spot.

You can see the original theme has a much higher contrast, which makes changes easier to see:

![Default theme](https://user-images.githubusercontent.com/13088397/81379949-516cb280-910a-11ea-9b78-92b31fd3faab.jpg)

**Comment by this-fifo** [comment]
I made a small tweak and thought it look more prominent while still using the same colors from primer

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/6960701/81705674-4cc33980-943d-11ea-9b51-040efa584dee.png">
