### ISSUE TITLE
Flutter: Dark theme changes color

### ISSUE THREAD

**Issue by Lee-BS-AMS** [primer/github-vscode-theme#183]
When using your dark theme with my flutter project in vscode, it originally looks like this
![before](https://user-images.githubusercontent.com/47419089/120927499-e7418b00-c6d8-11eb-9f88-c9e0d327307f.JPG)

but then after a minute switches to this. Any idea why??

![after](https://user-images.githubusercontent.com/47419089/120927523-ffb1a580-c6d8-11eb-89a0-772199a26b17.JPG)

**Comment by dominicegginton** [comment]
Have you got any extensions that change syntax highlighting colors when debugging?

**Comment by Lee-BS-AMS** [comment]
Fixed it, I had to turn off Semantic highlighting

**Comment by dominicegginton** [comment]
@Lee-BS-AMS I'm pleased you have found a solution, please can you close the issue 😀
