### ISSUE TITLE
Can I use branding inside the `nvim` port?

### ISSUE THREAD

**Issue by ful1e5** [primer/github-vscode-theme#186]
### Project Link:
[projekt0n/github-nvim-theme](https://github.com/projekt0n/github-nvim-theme/tree/dev)

**Comment by simurai** [comment]
Here are some [guidelines](https://github.com/logos) around using GitHub's logo and name.

I'm not a lawyer, but I would say https://github.com/projekt0n/github-nvim-theme is fine. There are [tons of themes](https://marketplace.visualstudio.com/search?term=GitHub&target=vscode&category=Themes&sortBy=Relevance) with the name GitHub in it and even use the logo.

If you're worried, you might can add a line like "This is an unofficial port of the [GitHub VS Code theme](https://github.com/primer/github-vscode-theme)" or similar.

Anyways, I'll close this again.

**Comment by ful1e5** [comment]
I just updated the repo description with (Unofficial Community-driven).
Thanks, for the reply.
