### ISSUE TITLE
improve scrollbar indicator visibility

### ISSUE THREAD

**Issue by HppZ** [primer/github-vscode-theme#196]
![image](https://user-images.githubusercontent.com/12285582/129844122-346855d8-2bb7-4dd6-9d62-ce2a5f59b144.png)

**Comment by sinsong** [comment]
same problem

guess where is the scrollbar
![scrollbar](https://user-images.githubusercontent.com/22849803/130095159-b20be1e6-dae0-4827-af3c-8225db92ff82.jpg)

**Comment by simurai** [comment]
Will be improved by https://github.com/primer/github-vscode-theme/pull/346.

**Comment by melyux** [comment]
It's still very faint and near impossible to see.
