### ISSUE TITLE
Improve `.json` readability

### ISSUE THREAD

**Issue by yzhang-gh** [primer/github-vscode-theme#20]
Thanks for the great theme!

However, the current theme is not that suitable for `.json` files, especially for `boolean` and `int` types.

![image](https://user-images.githubusercontent.com/7588612/81404039-3714f200-9167-11ea-8361-406f12a846e9.png)

It would be better to add most contrast.

**Comment by simurai** [comment]
Agreed that all the different blues makes JSON hard to read.

I guess it's the same question as in this [discussion](https://github.com/primer/github-vscode-theme/issues/19#issuecomment-627240537):

> How much should this "GitHub theme" try to mimic the syntax highlighting on github.com?

**Comment by simurai** [comment]
For reference https://github.com/primer/github-vscode-theme/issues/69#issuecomment-650467880

**Comment by jahamed** [comment]
Feel like this is one of the biggest problems with these theme right now too :/. I think the theme should be a 1 to 1 copy of github.com's theme, as users of this theme probably seek that out to context switch easier. Forks can always be made from the 'official theme'.
