### ISSUE TITLE
Opacity of minimap slider is too low

### ISSUE THREAD

**Issue by SL-Lee** [primer/github-vscode-theme#200]
# Steps to reproduce

1. Set the editor theme to **GitHub Dark Default**.
2. Enable the minimap and set `editor.minimap.showSlider` to `always`.
2. Open a long file (long enough to require scrolling in the editor area).

# Expected outcome

The opacity of the scrollbar and minimap slider is high enough to be easily seen.

# Actual outcome

The opacity of the scrollbar and minimap slider is too low to be easily seen.

Below is a screenshot illustrating this:

![image](https://user-images.githubusercontent.com/45960387/131224139-ac9fe9de-1ec4-4da0-9799-cb603208785c.png)

Changing the opacities of the minimap slider to match those of the scrollbar already makes it way easier on the eyes (I set `minimapSlider.background` to `#484f5833`, `minimapSlider.hoverBackground` to `#484f5844`, and `minimapSlider.activeBackground` to `#484f5888`, which match the colors of the corresponding scrollbar states), so I don't see why this is not the case already:

![image](https://user-images.githubusercontent.com/45960387/131224354-ec10fa6f-ec50-43bc-8d33-5072103612a6.png)

---

Extension version: `v4.1.1`

**Comment by github0null** [comment]
I think so, too;

Bad foreground and background contrast for minmap hover；Whenever I want to drag the slider, I can't find the location of the slider.  This is very bad
