### ISSUE TITLE
Find matches have low opacity

### ISSUE THREAD

**Issue by SL-Lee** [primer/github-vscode-theme#201]
# Steps to reproduce

1. Set the editor theme to **GitHub Dark Default**.
2. Open an editor containing some text.
3. Perform a search.

# Expected outcome

All find matches can be easily seen at a glance.

# Actual outcome

All find matches is not so easily seen at a glance, especially if searching for commonly occurring patterns in a wall of text.

Below is a screenshot illustrating this:

![image](https://user-images.githubusercontent.com/45960387/131224741-361b4bcf-0e3f-4c04-a2f6-11c4fd0c0562.png)

If I change `editor.findMatchBackground` to `#ffd33d66` and `editor.findMatchHighlightBackground` to `#ffd33d44` (increasing both settings' opacities by 22%), then it becomes much easier to see all find matches at a glance:

![image](https://user-images.githubusercontent.com/45960387/131224751-91d37346-cf4d-4dff-b0de-8a3386d21b5e.png)

---

Extension version: `v4.1.1`

**Comment by simurai** [comment]
I think this got improved in the meantime:

<img width="326" alt="Screen Shot 2022-07-15 at 20 47 12" src="https://user-images.githubusercontent.com/378023/179217239-82743991-c040-40fd-8e66-396283ae234f.png">
