### ISSUE TITLE
Remove classic theme in next major version

### ISSUE THREAD

**Issue by paramaggarwal** [primer/github-vscode-theme#204]
Today I realised that I was using the classic theme since so long because the updated one has a new name "GitHub Dark Default". As a user of this theme extension in VSCode, my goal is to get consistency with the UI within GitHub.com so that switching between the two is a consistent experience.

Hence I think we should boldly step forward and remove support for the classic themes in the next major version upgrade as well as removing the "Default" suffix.

**Comment by dominicegginton** [comment]
Thank you for opening an issue and sharing your thoughts. The community has discussed this at length (#139 #132 #123 #114). TLDR: classic themes are kept as some users didn't like the change to the new dark theme. The new themes are named 'Default' for consistency between VSCode, GitHub.com and Codespaces (Uses this theme as its default).

**Comment by paramaggarwal** [comment]
Oh ok, thanks 👍
