### ISSUE TITLE
4.2.0 color bug.

### ISSUE THREAD

**Issue by c0de2eat** [primer/github-vscode-theme#206]
Wrong color for the menu bars and side bars. All of them are in red. Attached is the screenshot.

![image](https://user-images.githubusercontent.com/89120933/132432454-e96dce48-07d9-4417-b317-40d149775e2a.png)

**Comment by simurai** [comment]
Ouch.. 🤦  @c0de2eat @calvojp92 thanks for notifying.

Should be fixed in `4.2.1`.
