### ISSUE TITLE
Light theme diff issues

### ISSUE THREAD

**Issue by zepfietje** [primer/github-vscode-theme#223]
Currently, selections inside a diff don't show in the light theme.
Also, the current line background highlight and highlight of text to show what specifically changed in the diff don't show.

I believe this is a regression, since it used to work correctly.

**Comment by simurai** [comment]
_Originally posted by @ridjis in https://github.com/primer/github-vscode-theme/issues/240#issuecomment-998678661_

---

From The diff views could be improved a bit in "Light High Contrast". Maybe some colors need to be semi-transparent to still see the selection?

![image](https://user-images.githubusercontent.com/11313640/146918273-aca0d1ad-7e23-4377-88fc-2d6f6af36d8e.png)
![image](https://user-images.githubusercontent.com/11313640/146918281-5e5453c5-f012-482f-87bd-63c9b6b29a11.png)

**Comment by maxbublik** [comment]
Just my 5 cents...
Special highlights for inserted/deleted symbols within modified lines are missing in `GitHub Light Default` theme.
But the highlights are present in the rest of the themes.

Light Default
<img width="1550" alt="GitHub Light Default" src="https://user-images.githubusercontent.com/620034/152690229-a509c30c-97f7-464c-a3fe-23ef30de7aaa.png">

Dark Dimmed
<img width="1543" alt="GitHub Dark Dimmed" src="https://user-images.githubusercontent.com/620034/152690239-d66ace9d-288b-42df-add5-72b909eea67a.png">

Dark Default
<img width="1554" alt="GitHub Dark Default" src="https://user-images.githubusercontent.com/620034/152690242-0fb6ed8f-38cd-4e06-a450-ef00100ec62e.png">

**Comment by jrieken** [comment]
> Maybe some colors need to be semi-transparent to still see the selection?

Yes, that's required for some colors. /cc @misolori for advice and maybe also idea how we can enforce this in vs code

**Comment by misolori** [comment]
The diff background colors definitely need transparency to let selection + highlights appear, the `diffEditor.insertedTextBackground` token on `GitHub Light Default` is @ 100% opacity:

<img width="565" alt="CleanShot 2022-02-07 at 20 07 54@2x" src="https://user-images.githubusercontent.com/35271042/152916478-39fa77c3-1381-4903-bb77-36dd4298f45d.png">

Dimming this can help:

<img width="550" alt="CleanShot 2022-02-07 at 20 09 10@2x" src="https://user-images.githubusercontent.com/35271042/152916547-498a60c8-8f69-4e41-aa49-e7a75a61f1c7.png">


<hr>


But also I think there might be some other issues going on the diff view as highlighting text for added/removed lines are fine when side by side:

<img width="593" alt="CleanShot 2022-02-07 at 20 01 15@2x" src="https://user-images.githubusercontent.com/35271042/152915895-0158a61a-6342-47be-b30e-26f9e68ed0d1.png">


but when in the diff view, some of the lines appear to be on separate layers:

<img width="570" alt="CleanShot 2022-02-07 at 20 01 43@2x" src="https://user-images.githubusercontent.com/35271042/152915951-bb32239d-9b9b-4406-899e-f9cf3183ca68.png">

This is a related but separate issue so I created https://github.com/microsoft/vscode/issues/142468 to follow up on it.

**Comment by zepfietje** [comment]
Recently a few others have reported this bug as well (https://github.com/primer/github-vscode-theme/issues/273, https://github.com/primer/github-vscode-theme/issues/277). Was wondering what's the status of this issue?

**Comment by simurai** [comment]
This should be fixed by https://github.com/primer/github-vscode-theme/pull/287

**Comment by zepfietje** [comment]
Awesome, thanks @simurai!
Should we wait for that PR to be merged manually?

**Comment by simurai** [comment]
> Should we wait for that PR to be merged manually?

Yes, but [`6.2.0`](https://github.com/primer/github-vscode-theme/pull/286) should be live now.

**Comment by zepfietje** [comment]
Great, thanks for fixing, @simurai!
