### ISSUE TITLE
Light has recently changed some colours and now the terminal has some parts that are too dark:

### ISSUE THREAD

**Issue by stellirin** [primer/github-vscode-theme#226]
Light has recently changed some colours and now the terminal has some parts that are too dark:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1012095/136839601-c9503465-ac6c-4f43-b836-7bb1dd93b88b.png"> 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1012095/136839687-6c578c37-8b70-4e57-bd25-e50446854dfa.png">

Compared to Dimmed:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1012095/136839817-8755bdc8-7102-414f-80a7-a91283238c34.png">
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1012095/136839856-190429b5-12ef-4668-842e-d02fcc73769f.png">

_Originally posted by @stellirin in https://github.com/primer/github-vscode-theme/discussions/217#discussioncomment-1460764_

**Comment by stellirin** [comment]
1. The colours are the defaults used by the [powerlevel10k](https://github.com/romkatv/powerlevel10k) plugin, pretty popular among developers (at least within my circles)
2. Other light themes don't have this issue
3. Github Light Default didn't have this issue until v5.0.0, v4.2.1 is that last 'useful' version

A small disagreement: the 'easiest' solution is to use the older version of the theme 😁

Ultimately, if updates to the theme have made text more difficult to read, then it's a faulure and it _should_ be considered a bug. I also hope the 'solution' is not like the previous solution which was to fork the theme internally and have two versions of light and dark in one package.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1012095/137024531-89de086c-99c0-4df7-91df-b83e4803860c.png">

**Comment by broccolinisoup** [comment]
This seems like it is resolved by [this commit](https://github.com/primer/github-vscode-theme/commit/a11a866610866c7dd0b4908c5fa8b61002b8992a) and please see the screenshots as well. I'm closing the issue but please let us know if you have any concerns 🙂 

<img width="320" alt="increased contrast on the terminal of VSCode using a zsh theme" src="https://user-images.githubusercontent.com/1446503/210923495-736e34ab-82e2-4422-a1ca-ac4f8fc8a2d4.png">
<img width="291" alt="increased contrast on the terminal of VSCode using a zsh theme" src="https://user-images.githubusercontent.com/1446503/210923502-342c0b4f-dd02-4fad-a483-0ed13b5fbac3.png">
