### ISSUE TITLE
Github Dark remote status text on status bar too light.

### ISSUE THREAD

**Issue by TinyBabyOwl** [primer/github-vscode-theme#227]
Here's what it looks like by default:
![image](https://user-images.githubusercontent.com/40748227/137247827-2099ffd4-5c76-4281-92f2-3ac73782cb0a.png)

Here's what it looks like setting the foreground color to black in the workbench.colorCustomizations file:
`"statusBarItem.remoteForeground":"#000000"`
![image](https://user-images.githubusercontent.com/40748227/137247912-0795bcf4-feb6-4824-b92a-76e277a476f8.png)

Could be helpful to make that a default color for that theme.

**Comment by LuigiZaccagnini** [comment]
Would love to work on this! Could you assign me to this issue?
