### ISSUE TITLE
GitHub Dark Colorblind theme break point not visible for color blind person

### ISSUE THREAD

**Issue by npalm** [primer/github-vscode-theme#245]
I just have tried the color blind dark theme, which works great. Nice Job! One setting that does not work for me is the color of the breakpoint

![image](https://user-images.githubusercontent.com/11609620/145983735-ecc63518-c68d-4e20-853e-264206e866a1.png)

I think using a light color for the breakpoint would be the best option for the contrast. Since the theme should address color blind people, I think it would be great to find a better default. What worked for me was overriding the theme in the settings file.

```json
{
        "workbench.colorCustomizations": {
            "debugIcon.breakpointForeground": "#000000"
        }
}
```

**Comment by simurai** [comment]
This PR https://github.com/primer/github-vscode-theme/pull/299 might improve the breakpoint icon for the colorblind themes.
