### ISSUE TITLE
[Light High Contrast] Improve diff views

### ISSUE THREAD

**Issue by simurai** [primer/github-vscode-theme#248]
The diff views could be improved a bit in "Light High Contrast". Maybe some colors need to be semi-transparent to still see the selection?

![image](https://user-images.githubusercontent.com/11313640/146918273-aca0d1ad-7e23-4377-88fc-2d6f6af36d8e.png)
![image](https://user-images.githubusercontent.com/11313640/146918281-5e5453c5-f012-482f-87bd-63c9b6b29a11.png)

---

_Originally posted by @ridjis in https://github.com/primer/github-vscode-theme/issues/240#issuecomment-998678661_

**Comment by zepfietje** [comment]
@simurai isn't this a duplicate of https://github.com/primer/github-vscode-theme/issues/223?
It's also an issue with the default light theme.

**Comment by simurai** [comment]
Ah... yes. Let's close this and move it over to #223
