### ISSUE TITLE
Active line number vs. muted line number in Light Theme (default)

### ISSUE THREAD

**Issue by 1081** [primer/github-vscode-theme#249]
No distinguishable difference between **active** `"editorLineNumber.activeForeground"` and **muted** `"editorLineNumber.foreground"` line number  in the  [Light Theme (default)](https://github.com/primer/primitives/blob/22e15240b18b7b18ab3193a759576fda8f611012/data/colors/themes/light.ts)

<img width="324" alt="Screenshot 2022-01-09 at 12 03 04" src="https://user-images.githubusercontent.com/11081331/148679636-25471975-01fb-4c35-85fc-a01c616092d0.png">

Suggestion: #57606a to #d0d7de
<img width="320" alt="Screenshot 2022-01-09 at 12 03 27" src="https://user-images.githubusercontent.com/11081331/148679646-b775400b-df51-47e6-ba0e-f440b7255c95.png">

change [here in line 6](https://github.com/primer/primitives/blob/48149b116a4708ad87712e6b13cfa1489f66cc0c/data/colors/vars/global_light.ts 
) `fg.muted` from `scale.gray.6` to `scale.gray.2` or maybe`scale.gray.3` 
or [here line 82](https://github.com/primer/primitives/blob/fc76170cc8e6ee59011d70857698867093f94d81/data/colors/vars/app_light.ts#L82)

**Comment by simurai** [comment]
Yeah, the different between active and the rest isn't that noticeable.

> to `scale.gray.2` or maybe`scale.gray.3`

This might be a bit too subtle and makes it hard to see non-active line numbers? In https://github.com/primer/github-vscode-theme/pull/298 I settle for `scale.gray.4`:

Before | After
--- | ---
![Screen Shot 2022-07-14 at 17 47 02](https://user-images.githubusercontent.com/378023/178943118-27a32c5d-788d-49df-9e80-a33b8fa23fbd.png) | ![Screen Shot 2022-07-14 at 17 46 11](https://user-images.githubusercontent.com/378023/178943107-511a3b82-cbfd-4fbe-b255-139312c5dc46.png)
