### ISSUE TITLE
Style in HTML is not colorized

### ISSUE THREAD

**Issue by rarodja** [primer/github-vscode-theme#251]
When you try to add a standalone style in html, it doesn't get colored like classes, I attach an example:

![issue](https://user-images.githubusercontent.com/74628132/150593122-4149442b-bb5b-445b-a359-bd9916f17791.png)

**Comment by simurai** [comment]
Hmm.. yeah. I'm not sure if it was added intentionally? Anyways, here a PR https://github.com/primer/github-vscode-theme/pull/297 to make it the same color as other strings.
