### ISSUE TITLE
Dimmed theme is broken in V5.2

### ISSUE THREAD

**Issue by jsantanders** [primer/github-vscode-theme#255]
Hi, an amazing theme, I love it.

I did notice v5.2 brokes the dimmed theme, the code is no longer being highlighted, this could be possibly caused by this PR https://github.com/primer/github-vscode-theme/pull/246

![image](https://user-images.githubusercontent.com/15827589/151491959-a88dff8e-96e6-46fe-a453-b5d999fd5017.png)

**Comment by epidemicz** [comment]
If you diff dark-dimmed.json between 5.1 and 5.2 and you can see a lot of stuff that just got simply stripped out.  I replaced the file with the one from 5.1 and that seemed to correct it.

**Comment by simurai** [comment]
@jsantanders Thanks for reporting. 🙇  Should be fixed with https://github.com/primer/github-vscode-theme/pull/256.
