### ISSUE TITLE
Feature Request: Please port this theme to IntelliJ Idea

### ISSUE THREAD

**Issue by Gaafar** [primer/github-vscode-theme#26]

**Comment by edokoa** [comment]
Pinging @simurai , as he's in charge of this.

**Comment by simurai** [comment]
@Gaafar I'm not too familiar how theming in IntelliJ Idea works. It might work with a "converter tool" like https://github.com/JetBrains/colorSchemeTool. There seems to be a `vscThemes` folder. So it might work with this theme too.. if you wanna give that a try.

**Comment by jsynowiec** [comment]
@Gaafar try those: https://gist.github.com/jsynowiec/f3570555174452bc8d73a1cda84db1e0
