### ISSUE TITLE
Light High Contrast Theme: problem with folder dropdown indicator and the blank spaces

### ISSUE THREAD

**Issue by JavierFuentes** [primer/github-vscode-theme#261]
I have just installed this great theme pack and I like very much "Light High Contrast Theme", but I can't see the folder dropdown indicator and the blank spaces are too visible...

<img width="324" alt="image" src="https://user-images.githubusercontent.com/5801847/153442619-201b07a8-c937-4d64-97e2-292bf221b2ef.png">

**Comment by yanmhlv** [comment]
Hey, also see this
<img width="540" alt="image" src="https://user-images.githubusercontent.com/1557291/154042821-da320ffc-7b63-4aa9-a648-a13679eac58f.png">
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/1557291/154042844-5b64af13-e6aa-4128-a436-1062a426dde4.png">
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1557291/154042913-dc29b3cc-2e78-45e1-8142-72afaed37dd5.png">

```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:56.651Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

**Comment by simurai** [comment]
This should be resolved by https://github.com/primer/github-vscode-theme/pull/285.

![image](https://user-images.githubusercontent.com/378023/178920804-68e2768d-88d5-4ac7-8872-8eed44558a08.png)
