### ISSUE TITLE
GitHub Light High Contrast icons hidden

### ISSUE THREAD

**Issue by zsy619** [primer/github-vscode-theme#264]
GitHub Light High Contrast part icons has hidden，why？？？
![067E2B04-2DF4-499D-AB65-5AA3CDA3B507](https://user-images.githubusercontent.com/6278792/156760507-6b391d2c-d66c-4dfe-b995-c8328fc3854d.png)
![96A81217-F032-41B8-97FA-1AF674B3C36B](https://user-images.githubusercontent.com/6278792/156760519-be8f9460-a732-4d39-b4e8-d593b2a1bf27.png)
![50229197-4FC8-4900-B1E6-954E4D9194D0](https://user-images.githubusercontent.com/6278792/156760528-d8e65e1e-d451-4dd0-81a2-f7d6f107767d.png)
![B896C239-8003-41B8-948C-D26FDE8FDD35](https://user-images.githubusercontent.com/6278792/156760536-dac0b255-d1d0-45d3-a069-57369631fc1b.png)

**Comment by dmalan** [comment]
Hi all, afraid we're seeing the same with **GitHub Light High Contrast**. E.g., notice the top-right, below. Only upon clicking (not just hovering) does the icon appear.

![image](https://user-images.githubusercontent.com/788678/161149179-ab771d9a-ca78-4e40-8e0d-d586e03dcde6.png)

CC @rongxin-liu

**Comment by Boiethios** [comment]
@dmalan I think this is an issue with this theme: the default light high contrast does not have this issue here.

The fix looks quite simple, the icons need to be black instead of being white.

That's a pity because I really like this theme otherwise.

**Comment by david8z** [comment]
Same here, possible workaround in the meantime add in settings.json:

```json
 "workbench.colorCustomizations": {
    "icon.foreground": "#000000"
}
```

**Comment by simurai** [comment]
> @david8z Same here, possible workaround in the meantime add in settings.json:

Thanks. Added this in https://github.com/primer/github-vscode-theme/pull/285.
