### ISSUE TITLE
[Python] class level constant not coloured like others (global/function scope)

### ISSUE THREAD

**Issue by michaeloliverx** [primer/github-vscode-theme#266]
Take the following snippet:
```python
GLOBAL_SCOPE_CONSTANT = 1


def function() -> None:
    FUNC_SCOPE_CONSTANT = 1

    print(FUNC_SCOPE_CONSTANT)


class Class:
    CLASS_SCOPE_CONSTANT = 1

```

Here is what it looks like with the `GitHub Dark Dimmed` theme:

![image](https://user-images.githubusercontent.com/55017335/158162109-80ab466e-8eab-49d5-8e4f-c352a9f0593f.png)

Should `CLASS_SCOPE_CONSTANT` not be coloured like the other constants?

**Comment by simurai** [comment]
Looks like this got resolved by accident? 🤔  Currently the code snippet above looks like:

![image](https://user-images.githubusercontent.com/378023/178915134-b240d79d-3b86-47bd-9ae9-41ccdb036d14.png)
