### ISSUE TITLE
Code in backticks in markdown file not coloured

### ISSUE THREAD

**Issue by AryanBeezadhur** [primer/github-vscode-theme#276]
GitHub theme:

![image](https://user-images.githubusercontent.com/34424160/165133183-ce3bb18a-13ca-4d2b-9b56-9ce11789e3a6.png)

Default theme:

![image](https://user-images.githubusercontent.com/34424160/165133274-1b20eaee-4feb-4320-b10a-74a08636bbe7.png)

**Comment by simurai** [comment]
Yeah, we might can do the same as in https://github.com/primer/github-vscode-theme/pull/193 also for the classic `GitHub Light` + `GitHub Dark`?
