### ISSUE TITLE
Add support for italics in the theme. 

### ISSUE THREAD

**Issue by khatterr** [primer/github-vscode-theme#280]
Many themes in the marketplace have italics support that makes a life a lot easier, especially in front end development. 

For eg:-  When the HTML markup is a large file then if the attributes are italicised, it would be a lot easier to look at and modify the markup.

Please provide support for this feature. It would be a life saver.

Thank You

**Comment by simurai** [comment]
Do you mean making HTML attributes italic, like in this example?

![Screen Shot 2022-07-13 at 17 06 55](https://user-images.githubusercontent.com/378023/178683818-5b815326-0cb5-4e88-8035-8e234e20ef95.png)

Hmm... in general, this theme tries to stay close to how github.com highlights HTML attributes which are non-italic. But we can convert this issue to a discussion and see if we get more feedback.
