### ISSUE TITLE
Why are github light and github dark theme not get updated frequently

### ISSUE THREAD

**Issue by mendax1234** [primer/github-vscode-theme#281]
From my perspective, the github dark default theme is too dimmed and the github dark theme is better , but l find that the github dark theme is different from the github.com , so why isn't github dark theme get updated?

**Comment by simurai** [comment]
`GitHub Dark` is an old theme. We tried to remove it, but there are still enough people that like to use it so we kept it.

The main goal of this theme is to try to stay close to github.com. So we started to use the same colors coming from https://primer.style/primitives/colors and they are not compatible with the old `GitHub Dark`.

Here also a discussion with more infos: https://github.com/primer/github-vscode-theme/discussions/114

**Comment by mendax1234** [comment]
Thanks!
