### ISSUE TITLE
The words in terminal is too dimmed

### ISSUE THREAD

**Issue by mendax1234** [primer/github-vscode-theme#282]
l use github dark default theme and l find that the words in this theme's terminal is too dimmed.
![image](https://user-images.githubusercontent.com/62934294/175756872-6f1ed79e-bca3-44c8-babf-3a5630dfaa8a.png)
And this is github dark's ones
![image](https://user-images.githubusercontent.com/62934294/175756875-6af616fb-4750-4d56-a68e-6a4a0b4356e6.png)
l wonder whther this can be fixed.
Thanks!

**Comment by mendax1234** [comment]
Thanks for the improvement!

**Comment by mendax1234** [comment]
So, when will this feature be available?

**Comment by simurai** [comment]
It should be live now as part of the [`6.2.0`](https://github.com/primer/github-vscode-theme/pull/286) release.
