### ISSUE TITLE
Is this theme liveupdated?

### ISSUE THREAD

**Issue by mendax1234** [primer/github-vscode-theme#283]
l find that primer has released the new CSS frequently, but this vscode theme seems to be a little out-of-date (according to the latest commit time). So l am confused whether this theme is liveupdated? @simurai

**Comment by simurai** [comment]
A new release just got published: https://github.com/primer/github-vscode-theme/releases/tag/v6.1.0

But yes, your observation is right that this theme doesn't get as many updates like other Primer projects. It's maintained more on a volunteer basis and only when time allows. Hopefully this week there will be more releases.
