### ISSUE TITLE
Absolutely gorgeous!

### ISSUE THREAD

**Issue by stevebauman** [primer/github-vscode-theme#29]
I had to create an issue here to say how happy I am with this stellar theme. I've always loved the code highlighting in GitHub, and now I have the same styling and appearance on my code editor that is on the web.

I've used PHPStorm for years, and honestly this theme is making me switch -- it's that pretty.

Thank you! ❤️

**Comment by paramaggarwal** [comment]
I feel the same! Excellent theme, so calm and polished.
