### ISSUE TITLE
The color of the files that are ignored by git is too dimmed

### ISSUE THREAD

**Issue by mendax1234** [primer/github-vscode-theme#290]
Theme l use: Github Dark Default
The color of the files that are ignored by git is too dimmed.

<img width="173" alt="image" src="https://user-images.githubusercontent.com/62934294/178883656-9c150ba5-18b6-4400-97bf-87ae156f74a2.png">

Hope this can be imporved!

**Comment by simurai** [comment]
I think this should be improved once we update to a newer version of [primer/primitives](https://github.com/primer/primitives).

`7.1.1` | `7.10.0`
--- | ---
![Screen Shot 2023-01-04 at 15 35 43](https://user-images.githubusercontent.com/378023/210503186-c8418ee9-92f5-4881-a30c-9ca32b7eb76b.png) | ![Screen Shot 2023-01-04 at 15 42 27](https://user-images.githubusercontent.com/378023/210503188-e99186d8-5a4e-4f41-a6cc-b21ced25be3c.png)
