### ISSUE TITLE
JSON in JavaScript files doesn't use the new colors for property names

### ISSUE THREAD

**Issue by SL-Lee** [primer/github-vscode-theme#318]
Thanks for the fix regarding the color for property names in JSON files (#303). However, JSON objects in JavaScript files still uses the old colors for property names (see the screenshot below), so it would be great if the same change can be applied to JSON objects in JavaScript files as well.

![image](https://user-images.githubusercontent.com/45960387/179815506-5e124034-8ab1-4b7a-a2c8-507ee5b204d4.png)

**Comment by SL-Lee** [comment]
I figured out that you can currently achieve this via token color customizations in VS Code as a temporary workaround:

```json
"editor.tokenColorCustomizations": {
  "[GitHub Dark Default]": {
    "textMateRules": [
      {
        "scope": "meta.object-literal.key.js string.quoted.double.js, meta.object-literal.key.js string.quoted.single.js",
        "settings": {
          "foreground": "#7EE787"
        }
      }
    ]
  }
},
```

Which results in the desired colors being applied for JSON property names in JavaScript files:

![image](https://user-images.githubusercontent.com/45960387/179818767-fba9e172-1bc6-4057-83af-5c001ba61f79.png)

**Comment by broccolinisoup** [comment]
👋🏼 Thanks for raising this PR. The current colour of the JSON property names in JS files are matching with github.com . Please see the screenshot below. The goal of this theme is to stay as close to [github.com](http://github.com/) as possible and you can read more about the motivation [here](https://github.com/primer/github-vscode-theme/discussions/345). I'm marking this issue as closed but please let us know if you have any concerns 🙌🏼 

<img width="316" alt="A JSON obj screenshot taken from github.com" src="https://user-images.githubusercontent.com/1446503/210687769-3452212d-405c-4e33-a035-fda404be4c67.png">
