### ISSUE TITLE
Too much blue in html dark-color-blind-theme

### ISSUE THREAD

**Issue by golam71** [primer/github-vscode-theme#329]
please add some yellow colors in html file
html is very clittered and using blue everywhere creates a mess
pls help

**Comment by simurai** [comment]
Mind posting some example code and a screenshot so it's easier to reproduce the issue.

**Comment by golam71** [comment]
u can see in the image below
just open a html file

![image](https://user-images.githubusercontent.com/74001687/210355112-d08c1bce-1330-43e0-b2d4-e19d0fe12c62.png)

my suggestion is to add some orange

**Comment by simurai** [comment]
What's the exact theme name you're using? Is it `GitHub Dark Default`?

With the following example code:

```html
<html lang="en">
  <head>
    <title>Img Width Attribute</title>
  </head>
  <body>
    <img src="image.png" alt="Image" width="100" />
  </body>
</html>
```

Elements/tags should be green and matches how github.com renders the same example code.

github.com | VS Code theme
--- | ---
![Screen Shot 2023-01-17 at 15 10 18](https://user-images.githubusercontent.com/378023/212823044-0e633cba-9281-4dce-aa76-43f9ff484735.png) | ![Screen Shot 2023-01-17 at 15 10 04](https://user-images.githubusercontent.com/378023/212823034-6ea8b855-dfdb-45cc-8b5c-83d5005a0f90.png)

**Comment by golam71** [comment]
@simurai  bro seriously 
the issue name says it is "dark-color-blind-theme"

i said i just want some other color in the colorblind theme 
currently if you type html in it it only has blue
![image](https://user-images.githubusercontent.com/74001687/212838842-ebe7d10a-27ed-4a93-8c6a-e5897dfa4730.png)

**Comment by golam71** [comment]
look bro using your example code
[github editor](https://github.dev/golam71/j/tree/main)
![image](https://user-images.githubusercontent.com/74001687/212841810-fc05038f-0993-4209-96ae-9de0a09b0f6b.png)

**Comment by golam71** [comment]
just add a bit of orange to it
its all blue 
hence it makes reading code very hard
i know colorblinds cant see many color but they can see 
so add some orange or yellow

**Comment by simurai** [comment]
> the theme name says it is "github-dark-color-blind"

Ahh.. sorry, I missed that in the title.

The colors are defined in https://primer.style/primitives/colors where green is mapped to blue. Since green is harder to see when colorblind. But best would be to not map it to another existing color otherwise there won't be a differentiation. Maybe this theme would need a custom override.

**Comment by golam71** [comment]
hmm makes sense
but adding a bit or orange is a good idea
because all blue is like no highlight 
give it a thought
