### ISSUE TITLE
Highlight colors in peekViewEditor 

### ISSUE THREAD

**Issue by orsenkucher** [primer/github-vscode-theme#38]
I believe now default very orange color is used, so you can barely read highlight text in `alt`+`F12` window. I want to suggest more sane colors for it😄. I'm using `dark` theme

```json
"peekViewEditor.matchHighlightBackground": "#ffd33d22", // or smth else :)
"peekViewResult.matchHighlightBackground": "#ffd33d22",
```

### Current one
![image](https://user-images.githubusercontent.com/15790628/82107375-ca35c500-972f-11ea-9d1b-c0846f2a88a9.png)

**Comment by this-fifo** [comment]
I noticed that too, I made some changes to improve it based on the rest of the theme

## Before
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/6960701/82109325-07379280-9703-11ea-978d-afbdc5b12064.png">

## After
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/6960701/82109366-5bdb0d80-9703-11ea-83f3-39bda4cc41bc.png">
