### ISSUE TITLE
Inline code block is not readable when using `GitHub Dark High Contrast` theme

### ISSUE THREAD

**Issue by babakfp** [primer/github-vscode-theme#380]
### Description

Hi

This is the markdown preview:

![image](https://github.com/primer/github-vscode-theme/assets/44144724/e6248f44-f9e5-4932-a8d2-70d381a78fba)

and it is the result of this markdown content:

![image](https://github.com/primer/github-vscode-theme/assets/44144724/6c7af91b-7273-4e1c-a9ee-ecfc682fd853)

I can confirm that this happens when all extensions (other than this one) are disabled.

### Steps to reproduce

Just switch to the `GitHub Dark High Contrast` theme and preview a markdown content in vsCode.

### Version

v6.3.4

### Theme

GitHub Dark High Contrast

**Comment by luctowers** [comment]
this is also the case for me

**Comment by luctowers** [comment]
Adding this to `settings.json` works as a hack.
```
"workbench.colorCustomizations": {
    "textPreformat.foreground": "#000000"
}
```

**Comment by babakfp** [comment]
> What type of font is used?
> 
> tks

https://www.jetbrains.com/lp/mono/

**Comment by babakfp** [comment]
> Adding this to `settings.json` works as a hack.
> 
> ```
> "workbench.colorCustomizations": {
>     "textPreformat.foreground": "#000000"
> }
> ```

Awesome, thank you. I changed your code to this:

```json
"workbench.colorCustomizations": {
    "textPreformat.background": "#3d3d3d"
},
```

and this is the result:

![image](https://github.com/primer/github-vscode-theme/assets/44144724/8bf9f042-b5f4-480d-a892-b0a6c0e4c4d5)

**Comment by j-w-yun** [comment]
> > Adding this to `settings.json` works as a hack.
> > ```
> > "workbench.colorCustomizations": {
> >     "textPreformat.foreground": "#000000"
> > }
> > ```
> 
> Awesome, thank you. I changed your code to this:
> 
> ```json
> "workbench.colorCustomizations": {
>     "textPreformat.background": "#3d3d3d"
> },
> ```
> 
> and this is the result:
> 
> ![image](https://private-user-images.githubusercontent.com/44144724/300540252-8bf9f042-b5f4-480d-a892-b0a6c0e4c4d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTM2MDMsIm5iZiI6MTcxODI1MzMwMywicGF0aCI6Ii80NDE0NDcyNC8zMDA1NDAyNTItOGJmOWYwNDItYjVmNC00ODBkLWE4OTItYjBhNmMwZTRjNGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA0MzUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZmQ0NTY2ZmFmMGQyYWY5ZWRkZThjNGJkMGU5YjE2N2NiOWI2NDVjYjgxNDI3MDk2ZTE4ZDNlYmY4YmI0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ceqM5TNjMsQMdMhJ0lGYTU8lm3bT49m9XgyWBSjH2_k)

Ugh, after years of squinting at these unreadable blocks I've finally found a solution. Thanks!

**Comment by Aethereal-Wraith** [comment]
@babakfp c
> Awesome, thank you. I changed your code to this:
> 
> ```json
> "workbench.colorCustomizations": {
>     "textPreformat.background": "#3d3d3d"
> },
> ```
> 
> and this is the result:
> 
> ![image](https://private-user-images.githubusercontent.com/44144724/300540252-8bf9f042-b5f4-480d-a892-b0a6c0e4c4d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODI4NjIsIm5iZiI6MTcyMTc4MjU2MiwicGF0aCI6Ii80NDE0NDcyNC8zMDA1NDAyNTItOGJmOWYwNDItYjVmNC00ODBkLWE4OTItYjBhNmMwZTRjNGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAwNTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZGE3N2M0ZTk1ZjgwMGIyNTc4NTVkYTBjOTI3NmY2OGUwODBjOWY4YmYxMmY2MjYxZWU0NjE5M2I4OTM5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Q-mzt1Oystsr4Agg-WDuYEyMnIQBTf19ecscnIoUbM)

the result looks great! I was looking on the [contribution guide](https://github.com/primer/github-vscode-theme?tab=readme-ov-file#contribute) in the README and it asks that contributions try to stick to the colours listed in the [Primer Design System](https://primer.style/foundations/color/base-scales#all-color-scales). The closest colour to your suggestion of `#3d3d3d` on the colour sheet is `#3d424d`, which is called `base-color-neutral-7`.
