### ISSUE TITLE
Github Markdown Support

### ISSUE THREAD

**Issue by perrychan1** [primer/github-vscode-theme#47]
Hope this can support GitHub Markdown favor, especially in checkbox. Or make a new extension for that. Current Markdown extensions on VS Code Market are not so good.

**Comment by simurai** [comment]
> Hope this can support GitHub Markdown favor, especially in checkbox.

@perrychan1 Do you mean when using the "Preview" feature? So that Markdown should be rendered with real checkbox in the preview window?

![image](https://user-images.githubusercontent.com/378023/82771325-97e63f00-9e76-11ea-9db6-797cf1c5aa8a.png)

**Comment by this-fifo** [comment]
There is a nice extension pack to add support to the built-in markdown preview window to look more like what you experience in GitHub, maybe that's what you want @perrychan1 

https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview

**Comment by perrychan1** [comment]
> > Hope this can support GitHub Markdown favor, especially in checkbox.
> 
> @perrychan1 Do you mean when using the "Preview" feature? So that Markdown should be rendered with real checkbox in the preview window?
> 
> ![image](https://user-images.githubusercontent.com/378023/82771325-97e63f00-9e76-11ea-9db6-797cf1c5aa8a.png)

yep.

**Comment by perrychan1** [comment]
@simurai Yes.

**Comment by perrychan1** [comment]
@this-fifo Great, thank you. This is a package, but I only need: 
- [Markdown Emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji)
- [Markdown Checkboxes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox)
