### ISSUE TITLE
White text is too bright 

### ISSUE THREAD

**Issue by simurai** [primer/github-vscode-theme#50]
This might be irrelevant to this issue but I feel using #fff as white in general is too bright in a dark theme and kind of hurts my eyes. I am not sure if the iOS app uses #fff as white but we can test that out.

_Originally posted by @icebeam030 in https://github.com/primer/github-vscode-theme/issues/19#issuecomment-635693787_

**Comment by simurai** [comment]
Yeah, I think we could consider making default text a bit darker. Or have an additional "high contrast" theme.

It depends a bit on the environment. In a dark room, white text could feel too bright. 👍

**Comment by orsenkucher** [comment]
ahaha yeah, yesterday evening I felt the same😜 and honestly default Dark+ felt a lot softer and easier to look in a dark room. But it really greatly depends on lighting conditions @simurai

**Comment by icebeam030** [comment]
I will try to create a PR to fix this over the weekend.
