### ISSUE TITLE
Markdown code blocks are too similar to regular text

### ISSUE THREAD

**Issue by dyang** [primer/github-vscode-theme#51]
When we edit markdowns in visual studio code, the code blocks are hardly visible with the github theme, e.g. compare `vsce publish [version]` in the first image to that in the second one (dracula):
<img width="274" alt="github" src="https://user-images.githubusercontent.com/33833/83339264-5d443280-a2cc-11ea-949a-6b85b4a4afc7.png">
<img width="307" alt="dracula" src="https://user-images.githubusercontent.com/33833/83339266-633a1380-a2cc-11ea-823e-c43fcc1c1f86.png">

**Comment by naiyerasif** [comment]
This is not only limited to code blocks, even emphasized and strongly emphasized text, links, etc appear indistinguishable from the rest of the text.

**Comment by RMeli** [comment]
In @dyang example the code blocks are hardly visible, but in other occasions they do not appear to be visible at all (at least to me).

For reference, I did rise this issue to the Jupyter extension and was moved to the main repository: https://github.com/microsoft/vscode/issues/125300

**Comment by simurai** [comment]
This should be fixed by https://github.com/primer/github-vscode-theme/pull/193
