### ISSUE TITLE
Hard to tell apart strings

### ISSUE THREAD

**Issue by domb5041** [primer/github-vscode-theme#56]
<img width="818" alt="Screenshot 2020-06-05 at 12 28 46" src="https://user-images.githubusercontent.com/33228675/83871574-36e92180-a728-11ea-8d5c-08a6bebac5bb.png">

applies to light version
strings look very similar to variables and key-value sets etc

**Comment by simurai** [comment]
For reference https://github.com/primer/github-vscode-theme/issues/69#issuecomment-650467880

**Comment by simurai** [comment]
Gonna close this as `wontfix`. For now we gonna keep this theme as close as possible to github.com, see https://github.com/primer/github-vscode-theme/discussions/345.
