### ISSUE TITLE
some syntax highlighting noticeably different to GitHub.com

### ISSUE THREAD

**Issue by domb5041** [primer/github-vscode-theme#57]
VS Code
<img width="822" alt="Screenshot 2020-06-05 at 12 34 23" src="https://user-images.githubusercontent.com/33228675/83872005-11a8e300-a729-11ea-9d85-96d0b539972d.png">

Github.com
<img width="845" alt="Screenshot 2020-06-05 at 12 34 33" src="https://user-images.githubusercontent.com/33228675/83872006-12417980-a729-11ea-8ec9-22cb5aa474bf.png">

**Comment by isa3bel** [comment]
will you expand on this issue? I don't see any highlighting in the second photo for Github.com

**Comment by domb5041** [comment]
Sorry I meant syntax highlighting colours. I have amended the issue title

**Comment by rileybrook** [comment]
Would love to see this theme's colors exactly match github.com (for familiarity)

**Comment by tamasvajk** [comment]
I found some differences for C# too. The following settings seems to fix it for the light theme. I'm still checking for other differences but at one point I'll include these in a PR.
```
"editor.tokenColorCustomizations": {
  "textMateRules":[
    {
      "scope": ["storage.type"],
      "settings": { "foreground": "#6f42c1" }
    },
    {
      "scope":["entity.name.variable"],
      "settings": { "foreground": "#24292e" }
    }
  ]
}
```
What seems a bit strange is that the `"storage.type"` is explicitly set to red in the theme. Was there a reason for this? GitHub.com uses purple for this (in C#).

**Comment by simurai** [comment]
Gonna close this as stale.
