### ISSUE TITLE
Make editor.lineHighlightBorder transparent, for better extension support

### ISSUE THREAD

**Issue by piersdeseilligny** [primer/github-vscode-theme#63]
The border around highlighted lines is currently invisible (I assume as a creative decision), however a better way of doing this than what is currently done would be to make `editor.lineHighlightBorder` transparent, in order to allow extensions to access this "creative decision". For example, this is what a highlighted line looks like in the default editor:

![image](https://user-images.githubusercontent.com/42496508/84580300-f0ee2680-add5-11ea-81e9-2f2f84ad994c.png)

However, the css code `var(--vscode-editor-lineHighlightBorder)` is still slightly grey, meaning that somehow `editor.lineHighlightBorder` has not actually been set as transparent by the theme, despite the border being hidden:

![image](https://user-images.githubusercontent.com/42496508/84580304-03686000-add6-11ea-96e5-1414a78d9d6e.png)

(this is also the case with the dark theme)

**Comment by simurai** [comment]
Hmm... This sounds like it's more an issue for https://github.com/microsoft/vscode? 🤔  Please re-open if not.
