### ISSUE TITLE
Search selection text is light focus and unreadable

### ISSUE THREAD

**Issue by shivapoudel** [primer/github-vscode-theme#64]
![Capture](https://user-images.githubusercontent.com/3774827/84629625-59d6bb00-af0a-11ea-92ce-60ea6d6041b2.PNG)

**Comment by shivapoudel** [comment]
@simurai Any update on this design issue?

**Comment by simurai** [comment]
Hmm.. yeah, search highlight + comments don't have a lot of contrast.. maybe we could

- make comments a bit lighter
- and search highlight a slightly darker

**Comment by shivapoudel** [comment]
@simurai already been a year and still this is not looked?

**Comment by simurai** [comment]
@shivapoudel Can you still reproduce the issue?

It should be fixed and the search result should be easier to read:

<img width="776" alt="Screen Shot 2021-07-14 at 16 16 12" src="https://user-images.githubusercontent.com/378023/125579780-78ffc7ab-3d7b-49d3-9e83-9a84b6c5698f.png">

**Comment by shivapoudel** [comment]
@simurai Seems like this is fixed. The theme was not updated now it is fixed so closing this ticket!
