### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by YevhenKap** [primer/github-vscode-theme#66]
I have installed extension, but on choosing theme VSCode shows an error - extension folder does not have `themes` directory with dark and light `json` files. This is confusing. I navigated to `.vscode-oss` folder with extension and inside `github.github-vscode-theme-1.1.2` made 
```sh
npm i; npm run build
```
Then extension start to work normally.

I use [VSCodium](https://vscodium.com) on Mac.

**Comment by simurai** [comment]
@YevhenKap Are you aware how VSCodium installs extensions? Does is pull them directly from the https://github.com/primer/github-vscode-theme repo?

The extension from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme) should have the `json` files included without having to `npm run build` first.

![Screen Shot 2020-06-24 at 14 29 21](https://user-images.githubusercontent.com/378023/85504521-26d9a900-b627-11ea-9bcd-e8ac8a9d5f21.png)

**Comment by owenvoke** [comment]
I'm getting this too (just installed VSCodium). According to their docs, it looks like VSCodium doesn't install from the VS Marketplace by default.
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

According to that, they mention that the easiest way seems to be to publish the extension to Open VSX. However, it looks like the GitHub theme is already there, but it uses the GitHub repository as the source so I guess it doesn't include the `themes` directory.
- https://open-vsx.org/extension/GitHub/github-vscode-theme
- https://github.com/open-vsx/publish-extensions/blob/bf5a7b9bbfe8dc32e8b75a0ba2068c43e9170c11/extensions.json#L282-L285

I guess a `"prepublish": "npm run build"` key could be added to the entry which would then run before the package gets published?

**Comment by simurai** [comment]
> I guess a `"prepublish": "npm run build"` key should be added to the entry which would then run before the package gets published?

@owenvoke Thanks for digging that up. ✌️  Yeah, adding `"prepublish": "npm run build"` might work. I'll see if I can make a PR in that repo.

**Comment by simurai** [comment]
This should be fixed 👉  https://github.com/open-vsx/publish-extensions/pull/63

In the future, it would be nice to use GitHub Actions to automate the releasing, https://github.com/open-vsx/publish-extensions/pull/63.

**Comment by owenvoke** [comment]
Thanks @simurai!

**Comment by jankeromnes** [comment]
> I guess this will be applied when the next release comes out?

Quick update: `v1.1.3` was just published to OpenVSX and includes @simurai's fix, so installing https://open-vsx.org/extension/GitHub/github-vscode-theme should work now.

**Comment by owenvoke** [comment]
Thanks! That's great, installed and it's working. 🎉 🥳

**Comment by YevhenKap** [comment]
Thanks a lot)
