### ISSUE TITLE
Ruby data types colors should be fixed

### ISSUE THREAD

**Issue by 3olkin** [primer/github-vscode-theme#67]
Colors of data typres in ruby are not the same. Example is on the screenshot:
![rb_colors_issue](https://user-images.githubusercontent.com/58516282/85615169-7db1a380-b664-11ea-86b3-d4a62b5961a9.png)

**Comment by simurai** [comment]
I _think_ this got fixed in the meantime and now all data types have the same (purple) color:

![Screen Shot 2023-01-05 at 15 21 35](https://user-images.githubusercontent.com/378023/210715009-f64c7ed6-6030-41f9-8f82-390a3712248a.png)
