### ISSUE TITLE
Some colors are hard to differentiate

### ISSUE THREAD

**Issue by bao007fei** [primer/github-vscode-theme#69]
Really love this theme. How about add some more color contrast in such cases. Thanks:D

![image](https://user-images.githubusercontent.com/24863266/85883533-b8a60980-b813-11ea-9ced-80d664ef117f.png)
![image](https://user-images.githubusercontent.com/24863266/85883556-c22f7180-b813-11ea-84ce-4070a990795d.png)

**Comment by simurai** [comment]
This came up a few times.. #19 + #20 + #56. And there is a PR trying to fix it: #54.

Here the [comment](https://github.com/primer/github-vscode-theme/pull/54#pullrequestreview-436382700) from that PR:

> But I'm not sure if it's fixable without also fixing github.com's syntax highlighting. 🤔  So far this theme was built with these restrictions:

> 1. Keep the colors to github.com as close as possible.
> 2. Keep the same hue for the light and dark version.

> We could disregard the two restrictions and experiment with different colors, but might be safer to initially do that as a separate theme that isn't used for [Codespaces](https://github.com/features/codespaces/).

So yeah, we would have to diverge from the syntax highlighting on github.com or maybe better yet: Change it in the VS Code theme **AND** on github.com.

**Comment by bao007fei** [comment]
> This came up a few times.. #19 + #20 + #56. And there is a PR trying to fix it: #54.
> 
> Here the [comment](https://github.com/primer/github-vscode-theme/pull/54#pullrequestreview-436382700) from that PR:
> 
> > But I'm not sure if it's fixable without also fixing github.com's syntax highlighting. 🤔  So far this theme was built with these restrictions:
> 
> > 1. Keep the colors to github.com as close as possible.
> > 2. Keep the same hue for the light and dark version.
> 
> > We could disregard the two restrictions and experiment with different colors, but might be safer to initially do that as a separate theme that isn't used for [Codespaces](https://github.com/features/codespaces/).
> 
> So yeah, we would have to diverge from the syntax highlighting on github.com or maybe better yet: Change it in the VS Code theme **AND** on github.com.

Thanks for the info. I would like to embrace the changes, both of them:D
