### ISSUE TITLE
List selection color is stronger than focus + selection

### ISSUE THREAD

**Issue by isidorn** [primer/github-vscode-theme#7]
Hi vscode dev here :wave:

Seen with GitHub light and GitHub sharp

1. Click on any list, for example explorer
2. Now the element is select and focused
3. Press down, now the elemnt up is just selected, but it has a darker shade than previously 🐛 

Selection + focus are stronger than just selection and thus the color should be stronger, not lighter.

I like your theme, thanks for that. 

State after step 2
![Screenshot 2020-04-24 at 10 58 32](https://user-images.githubusercontent.com/1926584/80194391-97aa1800-861a-11ea-8337-8cad9f70b48d.png)

State after step 3
![Screenshot 2020-04-24 at 10 58 36](https://user-images.githubusercontent.com/1926584/80194400-9a0c7200-861a-11ea-9eb2-1c79773820db.png)

**Comment by simurai** [comment]
@isidorn thanks for raising this issue.. 🙇 

> Selection + focus are stronger than just selection and thus the color should be stronger, not lighter.

Hmmm.. yeah, this seems tricky to fix. I couldn't find a way to change the "selected, but unfocused" color. 🤔 It seems that it gets [automatically darkened by 10%](https://github.com/microsoft/vscode/blob/8b7ea333ccc46fc8a27eda86199dfec57a4e255b/src/vs/platform/theme/common/styler.ts#L189) based on the `list.activeSelectionBackground` color. I assume that works ok for dark themes, but not really for light themes that use a selection color that is slightly darker than the background.

An option would be to make the `list.focusBackground` color even darker than the `darken(listActiveSelectionBackground, 0.1)`. But that feels a bit too dark:

![selection](https://user-images.githubusercontent.com/378023/80338312-f8de1f80-8896-11ea-957c-cbddafa9edd9.gif)

Or something like white text on a blue background, but it's still a bit odd that when the focus moves away from the selection that it becomes "stronger" (darker).

![selection-invert](https://user-images.githubusercontent.com/378023/80339429-933f6280-8899-11ea-9557-5a411cdc1a02.gif)

Would it be possible if VS Code would use `darken()` for dark themes and `lighten()` for light themes?

Or add a `list.focusAndSelectionBackground` token? But that's probably a lot more work. :grimacing:

**Comment by simurai** [comment]
This should be improved by now:

https://user-images.githubusercontent.com/378023/179155412-5a6c3bde-e9d7-4224-b0b1-31760bf64161.mov
