### ISSUE TITLE
Deliver to Github UI team haha, please

### ISSUE THREAD

**Issue by orsenkucher** [primer/github-vscode-theme#70]
Hey! Seems like a colorization bug😛😝
![image](https://user-images.githubusercontent.com/15790628/87094696-ff4e2780-c247-11ea-8225-cf038bd7c865.png)

**Comment by BinaryMuse** [comment]
@orsenkucher Thanks for the feedback; this repo is for the GitHub VSCode theme, but I'll make sure this gets to the right place.

**Comment by orsenkucher** [comment]
Yup, I know😄 This place is my local github minimum, like closest place to it
Thanks @BinaryMuse
