### ISSUE TITLE
How to change the line gutter color? 

### ISSUE THREAD

**Issue by nikitavoloboev** [primer/github-vscode-theme#73]
Maybe not relevant to the theme but how can I change this gutter color to be the same color as the background of the theme (`#ffffff` in light mode)?

![CleanShot 2020-08-04 at 11 56 54@2x](https://user-images.githubusercontent.com/6391776/89280941-9d67be80-d649-11ea-91c6-80b674c63a9c.png)

I thought to search `#f6f8fa` in this codebase but found nothing. I assume this theme doesn't set it?

I also tried to do:

```
  "workbench.colorCustomizations": {
    "editorGutter.background": "#ffffff",
  },
```

But that did nothing.

**Comment by simurai** [comment]
You could try `sideBar.border` and maybe also `activityBar.border` in case you hide the sideBar:

```
"workbench.colorCustomizations": {
  "activityBar.border": "#0000ff",
  "sideBar.border": "#ff0000",
},
```

![Screen Shot 2020-08-04 at 21 35 08](https://user-images.githubusercontent.com/378023/89294566-a46aed00-d69a-11ea-9d8d-5615a2a5c6eb.png)

**Comment by nikitavoloboev** [comment]
@simurai that is not what I wanted:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/6391776/94172944-77190f00-fe93-11ea-9fce-185fc67014d7.png">


<img width="448" alt="image" src="https://user-images.githubusercontent.com/6391776/94172967-7d0ef000-fe93-11ea-9cf9-6d017674e9e5.png">


I want to change this color:

![CleanShot 2020-09-24 at 18 26 49@2x](https://user-images.githubusercontent.com/6391776/94172999-88fab200-fe93-11ea-907a-cd3b0f67d36b.png)

I checked it's `#2a3037` but searching this code base, no results was found. I don't know what sets it. I basically want to remove it and make it same color as other lines `#222930`

**Comment by nikitavoloboev** [comment]
Like this:

<img width="146" alt="image" src="https://user-images.githubusercontent.com/6391776/94173115-b5163300-fe93-11ea-870a-f9181b2b34e0.png">

The above is from my vim config. I just want the number showing.

**Comment by nikitavoloboev** [comment]
Ok the answer was this 😻

`"editor.lineHighlightBackground": "#23292f"`
