### ISSUE TITLE
Link text in italicized Markdown blocks is not italicized

### ISSUE THREAD

**Issue by minimaxir** [primer/github-vscode-theme#74]
Occurs in both light and dark themes.

<img width="829" alt="Screen Shot 2020-08-09 at 10 10 46 AM" src="https://user-images.githubusercontent.com/2179708/89737815-fb6d1b00-da28-11ea-81f7-8ada916e93f7.png">

Compare to the default Dark+ theme:

<img width="827" alt="Screen Shot 2020-08-09 at 10 11 16 AM" src="https://user-images.githubusercontent.com/2179708/89737830-16d82600-da29-11ea-9157-85c041aef59e.png">

...although Dark+ does not italicize the hyperlink itself 🤷 

Dunno what the correct styling is here.

**Comment by simurai** [comment]
Hmm.. I'm not sure, but I think it's not possible to define the `string.other.link` AND `markup.italic` scope?

But anyways, not using an underline for the `[ ]` part (like Dark+ does it) seems even better, then only the URL that is actually clickable is underlined. I'll try to change it to that.
