### ISSUE TITLE
There is White (#ffffff) line in dark theme in bottom of maximized window on macOS

### ISSUE THREAD

**Issue by nikitavoloboev** [primer/github-vscode-theme#75]
It looks like this:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/6391776/89771136-21b1ba00-db00-11ea-97db-f414de4e4887.png">

I believe it's produced by the theme but it seems like a bug. It's distracting and it shouldn't be there. It should blend in with the colors of sidebar/editor/terminalv etc.

In case the screenshot above shows it unclearly, here is a closeup of it:

<img width="95" alt="image" src="https://user-images.githubusercontent.com/6391776/89771290-5cb3ed80-db00-11ea-8b97-b0ad404b50f3.png">

Can replicate it 100% of times on vscode version 1.48.0-insider and macOS.

**Comment by nikitavoloboev** [comment]
Oh and I just noticed, it's only there when window is maximized. If you move window from bottom of screen, white bar disappears.

**Comment by simurai** [comment]
Hmm.. I can't reproduce it. Wonder if it's an extension or some sort of setting that adds that line? 🤔

**Comment by nikitavoloboev** [comment]
Ok it seems to have disappeared for me too. Perhaps some odd VSCode update.
