### ISSUE TITLE
Complete theming

### ISSUE THREAD

**Issue by jeffgennari** [primer/github-vscode-theme#76]
Any chance you can add additional theming elements, such as symbolIcon.* and debugTokenExpression.* to the themes? For example, something like the following for debug tokes in Github Dark would give the theme a more complete feel: 

 `"debugTokenExpression.name": "#79b8ff",
            "debugTokenExpression.value": "#9ECBFF",
            "debugTokenExpression.string": "#9ECBFF",
            "debugTokenExpression.boolean": "#85E89D",
            "debugTokenExpression.number": "#85E89D",
            "debugTokenExpression.error": "#F97583",
`

**Comment by simurai** [comment]
Should be added with https://github.com/primer/github-vscode-theme/pull/239
