### ISSUE TITLE
How to change the colors of the lines delimiting tab's name?

### ISSUE THREAD

**Issue by RiccardoMPesce** [primer/github-vscode-theme#78]
Hi, how do I change the colors (or eventually removing) of the lines delimiting the name?

These are the ones

![image](https://user-images.githubusercontent.com/20295325/91631236-62eb0a80-e9d8-11ea-990c-d746a5f68c29.png)
 Thanks

**Comment by simurai** [comment]
Do you mean the red/coral line at the top of a tab?

![Screen Shot 2020-09-03 at 14 15 18](https://user-images.githubusercontent.com/378023/92074019-0466c780-edf0-11ea-871e-b9496225ac42.png)

I think that comes from https://github.com/primer/github-vscode-theme/blob/9da40f8cac56ca91863b7e97a89e25ce0991632c/src/theme.js#L122.

And can be changed with the following in your `settings.json`:

```json
"workbench.colorCustomizations": {
  "tab.activeBorderTop": "#ffff00",
},
```

Not sure about the blue line at the bottom. When does that show up? Is it another extension?

**Comment by RiccardoMPesce** [comment]
Hello,

sorry for the belated reply but I had to move.

![image](https://user-images.githubusercontent.com/20295325/92323515-c52bb700-f039-11ea-97b5-bd4669b7d8ee.png)

These are the extensions I have. Lines show up only when the tab is focused. Otherwise no. Like this

![image](https://user-images.githubusercontent.com/20295325/92323545-f86e4600-f039-11ea-98bc-9e47a4e71517.png)

**Comment by simurai** [comment]
Hmm.. very strange. Can't reproduce the "blue line on focus". 🤔   Instead of an extension, it could also be a VS Code setting that needs to be toggled on to see the blue underline?

**Comment by RiccardoMPesce** [comment]
The "incriminated" setting was: "tab.activeBorder".
![image](https://user-images.githubusercontent.com/20295325/92404193-3ef39b80-f133-11ea-8777-3dd8e7fb1e5d.png)

Problem now solved. Thanks.
