### ISSUE TITLE
Color issue on status bar

### ISSUE THREAD

**Issue by junyicc** [primer/github-vscode-theme#87]
Hi, all

Absolute white background on status bar may cause the following color issue:

![image](https://user-images.githubusercontent.com/10704251/94522885-f1b2a780-0262-11eb-8d3c-8fbd2902d07b.png)

Actually， it is "Select Python Interpreter".

![image](https://user-images.githubusercontent.com/10704251/94523027-2a528100-0263-11eb-9b33-81dc2bceea80.png)

**Comment by simurai** [comment]
Any steps how to reproduce this issue?
