### ISSUE TITLE
When using this theme, the cursor in the terminal disappeared

### ISSUE THREAD

**Issue by Zhan-Jie** [primer/github-vscode-theme#89]

**Comment by simurai** [comment]
@Zhan-Jie I can't reproduce this. Mind posting a screenshot? It should show as a block like this:

![Screen Shot 2020-11-02 at 11 51 54](https://user-images.githubusercontent.com/378023/97825405-e63f1a00-1d01-11eb-8098-0f42178e5ccb.png)
