### ISSUE TITLE
Colours don’t match with GitHub dark mode

### ISSUE THREAD

**Issue by arzg** [primer/github-vscode-theme#96]
GitHub [now has an official dark mode](https://techcrunch.com/2020/12/08/github-gets-a-dark-mode/). The colour palette it uses for code doesn’t match that of the VS Code theme:

<img width="441" alt="Screen Shot 2020-12-09 at 11 19 53 pm" src="https://user-images.githubusercontent.com/31783266/101629178-0c7c7600-3a75-11eb-84c1-ca1019ea5828.png">

<img width="506" alt="Screen Shot 2020-12-09 at 11 20 10 pm" src="https://user-images.githubusercontent.com/31783266/101629201-169e7480-3a75-11eb-98fd-e0609a3ca1c6.png">

**Comment by erictaylor** [comment]
#95

**Comment by simurai** [comment]
Closed by #102
